const commonHints = [
  'active',
  'recovered',
  'deceased',
  'cases',
  'new',
  'test',
  'tested',
  'so far',
  'confirmed',
  'active cases',
  'recovered cases',
  'deceased cases',
  'confirmed cases',
  'tested cases',
  'test cases',
  'death',
  'died',
  'India',
  'Adilabad',
  'Telangana',
  'Agar Malwa',
  'Agra',
  'Uttar Pradesh',
  'Ahmadabad',
  'AmdavadGujarat',
  'Ahmadnagar',
  'Ahmednagar',
  'Maharashtra',
  'Aizawl',
  'Mizoram',
  'Ajmer',
  'Rajasthan',
  'Akola',
  'Alappuzha',
  'Aligarh',
  'Alipurduar',
  'alipurdwar West Bengal',
  'Alirajpur',
  'Almora',
  'Dwarahat',
  'Ranikhet',
  'Someshwar',
  'Jageshwar',
  'Uttarakhand',
  'Alwar',
  'Ambala',
  'Mulana',
  'Naraingarh',
  'Haryana',
  'Ambedkar Nagar',
  'AkbarpurUttar Pradesh',
  'Amethi',
  'Amravati',
  'Amreli',
  'Anumanji',
  'Amlik',
  'Amravat',
  'Gujarat',
  'Amritsar',
  'Punjab',
  'Amroha',
  'Jyotiba Phule Nagar',
  'Azizpura',
  'Anand',
  'Khambhat',
  'Karamsad',
  'Tarapur',
  'Petlad',
  'Sojitra',
  'Anantapur',
  'Anantapuramu',
  'Hindupur',
  'Andhra Pradesh',
  'Anantnag',
  'Anjaw',
  'Hawai Arunachal Pradesh',
  'Anugul',
  'Anuppur',
  'Bihar',
  'Araria',
  'Aravalli',
  'Modasa',
  'Ariyalur',
  'Arwal',
  'Ashoknagar',
  'Auraiya',
  'Kannauj',
  'Etawah',
  'Aurangabad',
  'Azamgarh',
  'Azamgadh Uttar Pradesh',
  'Badgam',
  'Bagalkote',
  'Karnataka',
  'Bageshwar',
  'Baghpat',
  'Bahraich',
  'Baksa',
  'Assam',
  'Balaghat',
  'Balangir',
  'Baleshwar',
  'Ballari',
  'Ballia',
  'Balod',
  'Dalli Rajhara Chhattisgarh',
  'Baloda Bazar',
  'Bhatapara Chhattisgarh',
  'Balrampur',
  'Kusmi',
  'Rajpur',
  'Ramanujganj',
  'Ramchandarpur',
  'Shankargarh',
  'Wadrafnagar',
  'Chhattisgarh',
  'Bametara',
  'Nawagarh',
  'Saja',
  'Banas Kantha',
  'banaskantha Gujarat',
  'Banda',
  'Bandipore',
  'Banka',
  'Bankura',
  'West Bengal',
  'Banswara',
  'Bara Banki',
  'BarabankiUttar Pradesh',
  'Baramula',
  'Baran',
  'Bareilly',
  'Bargarh',
  'Barmer',
  'Barnala',
  'Barpeta',
  'Barwani',
  'Bastar',
  'Darba',
  'Frezarpur',
  'Hatkachora',
  'Jagdalpur',
  'Sosanpal',
  'Basti',
  'Bathinda',
  'Baudh',
  'Begusarai',
  'Belagavi',
  'Bengaluru',
  'Bengaluru Rural',
  'Betul',
  'Odisha',
  'Bhadohi',
  'Bhadradri Kothagudem',
  'Kothagudem Telangana',
  'Bhadrak',
  'Bhagalpur',
  'Bhandara',
  'Bharatpur',
  'Bharuch',
  'broach',
  'Amirgadh',
  'Bhabhar',
  'Dantiwada',
  'Danta',
  'Deesa',
  'Deodar',
  'Dhanera',
  'Palanpur',
  'Sihori',
  'Kankrej',
  'Tharad',
  'Vadgam',
  'Lakhni',
  'Suigam',
  'Vav',
  'Bhavnagar',
  'Sihor',
  'Umrala',
  'Gariadhar',
  'Palitana',
  'Mahuva',
  'Talaja',
  'Ghogha',
  'Jesar',
  'Vallbhipur.',
  'Bhilwara',
  'Bhind',
  'Bhiwani',
  'Loharu',
  'Siwani',
  'Tosham',
  'Bhojpur',
  'ArrahBihar',
  'Bhopal',
  'Bid',
  'Beed',
  'Bidar',
  'Bijapur',
  'Bhopalpatnam',
  'Bijnor',
  'Bikaner',
  'Bilaspur',
  'Baitalpur',
  'Bilha',
  'Bodri',
  'Deori',
  'Gaurella',
  'Ghutku',
  'Kota',
  'Lingiyadih',
  'Mehmand',
  'Pendra',
  'Ratanpur',
  'Sirgiti',
  'Takhatpur',
  'Himachal Pradesh',
  'Birbhum',
  'Bishnupur',
  'Manipur',
  'Biswanath',
  'Biswanath Chariali',
  'Bokaro',
  'Jharkhand',
  'Bongaigaon',
  'Botad',
  'Bitad',
  'Gadhada',
  'Barvala',
  'Ranpur',
  'Budaun',
  'Bulandshahr',
  'Bulandshahar',
  'Khurja',
  'Buldana',
  'BuldhanaMaharashtra',
  'Bundi',
  'Burhanpur',
  'Buxar',
  'BalliaBihar',
  'Cachar',
  'Central Delhi',
  'Cannaught Place',
  'CP',
  'Delhi',
  'Chamarajanagara',
  'Chamba',
  'Chamoli',
  'Badrinath',
  'Karnprayag',
  'Tharali',
  'Champawat',
  'Champhai',
  'Chandauli',
  'Chandel',
  'Chandigarh',
  'Chandrapur',
  'Changlang',
  'Arunachal Pradesh',
  'Charaideo',
  'Charki Dadri',
  'BadhraHaryana',
  'Chatra',
  'Chennai',
  'Chhatarpur',
  'Chhindwara',
  'Chikkaballapura',
  'Chikkamagaluru',
  'Chirang',
  'Chitradurga',
  'Chitrakoot',
  'Chittaurgarh',
  'Chittoor',
  'Chota Udaipur',
  'Chhota Udepur',
  'Pavi Jetpur',
  'Kawant',
  'Naswadi',
  'Sankheda',
  'Bodeli',
  'Churachandpur',
  'Churu',
  'Coimbatore',
  'Cooch Behar',
  'Coochbehar',
  'Koch Bihar',
  'Cuddalore',
  'Cuttack',
  'Dadra and Nagar Haveli',
  'Dakshin Bastar Dantewada',
  'Bade Bacheli',
  'Dantewada',
  'Geedam',
  'Katekalyan',
  'Kirandul',
  'Kuwakonda',
  'Penta',
  'Dakshin Dinajpur',
  'South DinajpurWest Bengal',
  'Dakshina Kannada',
  'Daman',
  'Daman And Diu',
  'Damoh',
  'Darbhanga',
  'Darjeeling',
  'Darrang',
  'Datia',
  'Dausa',
  'Davanagere',
  'Debagarh',
  'Dehradun',
  'Mussoorie',
  'Rishikesh',
  'Deoghar',
  'Deoria',
  'Devbhumi Dwarka',
  'Dwarka',
  'Bhanvad',
  'Kalyanpur',
  'Khambaila',
  'Dewas',
  'Dhalai',
  'Tripura',
  'Dhamtari',
  'Bagoud',
  ' Kurud',
  'Nagri',
  'Dhanbad',
  'Dhar',
  'Pithampur Madhya Pradesh',
  'Dharmapuri',
  'dharmapuriTamil Nadu',
  'Dharwad',
  'Dhaulpur',
  'Dhemaji',
  'Dhenkanal',
  'Dhubri',
  'Dhule',
  'Dibrugarh',
  'Dima Hasao',
  'Dimapur',
  'Nagaland',
  'Dindigul',
  'Dindori',
  'Diu',
  'Doda',
  'Dohad',
  'Dahod',
  'Jhalod',
  'Devgarh',
  'Garbada',
  'Limkheda',
  'Fatehpur',
  'Dhanpur',
  'Sanjeli',
  'Dumka',
  'Dungarpur',
  'Durg',
  'Bhilai',
  ' Durg',
  ' Ahiwara',
  'Bhilai Charoda',
  'Dhamdha',
  'Jamul',
  'Khamhria',
  'Kumhari',
  'Mahamaya',
  'Parpodi',
  'Patan',
  'East Champaran',
  'East Delhi',
  'Dilshad Garden',
  'Mayur vihar',
  'Parpatganj',
  'East District',
  'Sikkim East District',
  'Sikkim East',
  'Sikkim',
  'East Garo Hills',
  'Meghalaya',
  'East Godavari',
  'Kakinada Andhra Pradesh',
  'East Jaintia Hills',
  'East Kameng',
  'Seppa Arunachal Pradesh',
  'East Khasi Hills',
  'East Siang',
  'Pasighat  Arunachal Pradesh',
  'Ernakulam',
  'Erode',
  'Etah',
  'Faizabad',
  'AyodhyaUttar Pradesh',
  'Faridabad',
  'Nuh',
  'Palwal',
  'Faridkot',
  'Farrukhabad',
  'FategarhUttar Pradesh',
  'Fatehabad',
  'Ratia',
  'Tohana',
  'Fatehgarh Sahib',
  'Fazilka',
  'AboharPunjab',
  'Firozabad',
  'ShikohabadUttar Pradesh',
  'Firozpur',
  'Gadag',
  'Gadchiroli',
  'Gajapati',
  'Ganderbal',
  'Gandhinagar',
  'Motera',
  'Adala',
  'Kalol INA',
  'Dahegam',
  'Mansa',
  'Ganganagar',
  'Ganjam',
  'BerhampurOdisha',
  'Garhwa',
  'Gariaband',
  'Gariaband Chhattisgarh',
  'Gautam Buddha Nagar',
  'Noida',
  'Greater Noida',
  'Gaya',
  'Ghaziabad',
  'ModinagarUttar Pradesh',
  'Ghazipur',
  'Gir Somnath',
  'Veraval',
  'Talala',
  'Sutrapada',
  'Kodinar',
  'Una',
  'Gir-Gadhada',
  'Giridih',
  'Goalpara',
  'Godda',
  'Golaghat',
  'Gomati',
  'Gonda',
  'Gondiya',
  'GondiaMaharashtra',
  'Gopalganj',
  'Gorakhpur',
  'Gumla',
  'Guna',
  'Guntur',
  'Gurdaspur',
  'BatalaPunjab',
  'Gurugram',
  'Sohna',
  'Pataudi',
  'Farukh Nagar',
  'Manesar',
  'gurgaon',
  'Gwalior',
  'Hailakandi',
  'Hamirpur',
  'Hanumangarh',
  'Hapur',
  'Harda',
  'Hardoi',
  'Haridwar',
  'Roorkee Uttarakhand',
  'Hassan',
  'Hathras',
  'Haveri',
  'Hazaribagh',
  'Hingoli',
  'Hisar',
  'Adampur',
  'Agroha',
  'Barwala',
  'Hansi',
  'Narnaund',
  'Uklanamandi',
  'Hojai',
  'Hooghly',
  'Hoogli',
  'Hugli',
  'Hoshangabad',
  'ItarsiMadhya Pradesh',
  'Hoshiarpur',
  'Howrah',
  'Hyderabad',
  'Idukki',
  'Imphal East',
  'Imphal West',
  'Indore',
  'Jabalpur',
  'Jagatsinghapur',
  'Jagitial',
  'Jaipur',
  'Jaisalmer',
  'Jajapur',
  'Jalandhar',
  'Jalaun',
  'OraiUttar Pradesh',
  'Jalgaon',
  'BhusawalMaharashtra',
  'Jalna',
  'Jalore',
  'Jalpaiguri',
  'Jammu',
  'Jamnagar',
  'Jam Jodhpur',
  'Jodiya',
  'DhrolJamnagar',
  'Lalpur',
  'Kalavad',
  'Jamtara',
  'Jamui',
  'Jangoan',
  'Janjgir Champa',
  'Adbhar',
  'Akaltara',
  'Baloda',
  'Champa',
  'Janjgir',
  'Kharod',
  'Naila-Janjgir',
  'Naya Baradwar',
  'Pamgarh',
  'Sakti',
  'Shivrinarayan',
  'Jashpur',
  'Jashpur Nagar',
  'Kunkuri',
  'Pathalgaon',
  'Jaunpur',
  'Jayashankar',
  'Bhupalpalle',
  'Jayashankar Bhupalpally',
  'Jehanabad',
  'Jhabua',
  'Jhajjar',
  'Bahadurgarh',
  'Badli',
  'Beri',
  'Jhalawar',
  'Jhansi',
  'Jhargram',
  'Jharsuguda',
  'Jhunjhunu',
  'Jind',
  'Narwana',
  'Safidon',
  'Jiribam',
  'Jodhpur',
  'Jogulamba Gadwal',
  'Gadwal Telangana',
  'Jorhat',
  'Junagadh',
  'Bhesan',
  'Junagadhl',
  'Keshod',
  'Malia',
  'Manavadar',
  'Mangrol',
  'Mendarda',
  'Vanthali',
  'Visavadar',
  'Kabeerdham',
  'Kabirdham',
  'Chilpi',
  'Kawardha',
  'Pandariya',
  'Pandatarai',
  'Kachchh',
  'Abdasa',
  'Anjar',
  'Bhachau',
  'Bhuj',
  'Gandhidham',
  'Lakhpat',
  'Mandvi',
  'Mundra',
  'Nakhatrana',
  'Rapar',
  'Kaimur Bhabua',
  'Kaithal',
  'Guhla',
  'Pundri',
  'Kalayat',
  'Kakching',
  'Kalaburagi',
  'Gulbarga Karnataka',
  'Kalahandi',
  'bhawanipatna Odisha',
  'Kalimpong',
  'Kamareddy',
  'Kamjong',
  'Kamle',
  'Khamle',
  'Raga',
  'Kamrup',
  'Kamrup Metropolitan',
  'Guwahati Assam',
  'Kancheepuram',
  'Kanchipuram Tamil Nadu',
  'Kandhamal',
  'Kangpokpi',
  'Kangra',
  'Kanker',
  'Bhanupratappur',
  'Kapsi',
  'Pakhanjore',
  'Kanniyakumari',
  'Kanyakumari Tamil Nadu',
  'Kannur',
  'Kerala',
  'Kanpur Dehat',
  'Kanpur Nagar',
  'Kanpur city',
  'Kanpur',
  'Kapurthala',
  'Phagwara Punjab',
  'Karaikal',
  'Puducherry',
  'Karauli',
  'Karbi Anglong',
  'Kargil',
  'Ladakh',
  'Karimganj',
  'Karimnagar',
  'Karnal',
  'Nilokheri',
  'Indri',
  'Gharaunda',
  'Assandh',
  'Karur',
  'Kasaragod',
  'Kasganj',
  'Kathua',
  'Katihar',
  'Katni',
  'Murwara Madhya Pradesh',
  'Kaushambi',
  'Kendrapara',
  'Kendujhar',
  'Khagaria',
  'Khammam',
  'Khandwa',
  'East Nimar Madhya Pradesh',
  'Khargone',
  'West Nimar Madhya Pradesh',
  'Kheda',
  'Nadiad',
  'Thasra',
  'Kapadvanj',
  'Mehmedabad',
  'Kathlal',
  'Matar',
  'Mahudha',
  'Kaira',
  'Kheri',
  'Lakhimpur Kheri Uttar Pradesh',
  'Khordha',
  'Bhubhaneshwar Odisha',
  'Khowai',
  'Khunti',
  'Kinnaur',
  'Kiphire',
  'Kishanganj',
  'Kishtwar',
  'Kodagu',
  'coorg Karnataka',
  'Kodarma',
  'Kohima',
  'Kokrajhar',
  'Kolar',
  'Kolasib',
  'Kolhapur',
  'Kolkata',
  'Calcutta West Bengal',
  'Kollam',
  'Kondagaon',
  'Keskal',
  'Pharasgaon',
  'Koppal',
  'Koraput',
  'Korba',
  'Banki Mongra',
  'Dipka',
  'Katghora',
  'Rajgamar',
  'Koriya',
  'Baikunthpur',
  'Chharchha',
  'Chirmiri',
  'Jhagrakhand',
  'Khongapani',
  'Manendragarh',
  'Kottayam',
  'Kozhikode',
  'Kra Daadi',
  'New Palin',
  'Jamin',
  'Krishna',
  'Vijayawada',
  'Machilipatnam',
  'Krishnagiri',
  'Kulgam',
  'Kullu',
  'Kumuram Bheem Asifabad',
  'Asifabad Telangana',
  'Kupwara',
  'Kurnool',
  'Kurukshetra',
  'Thanesar',
  'Pehowa',
  'Kurung Kumey',
  'Koloriang Arunachal Pradesh',
  'Kushinagar',
  'Lahul and Spiti',
  'Lakhimpur',
  'Lakhisarai',
  'Lakshadweep',
  'Lalitpur',
  'Latehar',
  'Latur',
  'Lawngtlai',
  'Leh',
  'Lepa Rada',
  'Basar Arunachal Pradesh',
  'Lohardaga',
  'Lohit',
  'Tezu Arunachal Pradesh',
  'Longding',
  'Longleng',
  'Lower Dibang Valley',
  'Roing Arunachal Pradesh',
  'Lower Siang',
  'LikabaliArunachal Pradesh',
  'Lower Subansiri',
  'ZiroArunachal Pradesh',
  'Lucknow',
  'Ludhiana',
  'Lunglei',
  'Madhepura',
  'Madhubani',
  'Madurai',
  'Mahabubabad',
  'Mahabubnagar',
  'Mahasamund',
  'Bagbahara',
  'Basna',
  'Pithora',
  'Saraipali',
  'Sirpur',
  'Mahe',
  'Mahendragarh',
  'Narnaul',
  'Nangal Chowdhary',
  'Kanina Mahendragarh',
  'Ateli',
  'Mahesana',
  'Vijapur',
  'Bahucharaji',
  'Satlasana',
  'Modhera',
  'Unjha',
  'Vadnagar',
  'Kalol',
  'Kadi',
  'Visnagar',
  'Kherva',
  'Jotana',
  'Kheralu',
  'Mahisagar',
  'Balasinor',
  'Lunavada',
  'Kadana',
  'Virpur',
  'Santrampur',
  'Khanpur',
  'Mahoba',
  'Mahrajganj',
  'Mainpuri',
  'Majuli',
  'Malappuram',
  'Maldah',
  'Malda',
  'Maldaha',
  'Malkangiri',
  'Mamit',
  'Mancherial',
  'Mandi',
  'Mandla',
  'Mandsaur',
  'Mandya',
  'Mathura',
  'Vrindavan',
  'Mathura Vrindavan',
  'Mau',
  'Mayurbhanj',
  'baripada Odisha',
  'Medak',
  'Medchal Malkajgiri',
  'Medinipur East',
  'Purba Medinipur',
  'East Medinipur',
  'East Midnapore',
  'Midnapore East',
  'Medinipur West',
  'Paschim Medinipur',
  'West Midnapore',
  'Midnapore West',
  'Meerut',
  'Mirpur',
  'Mirzapur',
  'Moga',
  'Mokokchung',
  'Mon',
  'Moradabad',
  'Morbi',
  'Maliya',
  'Tankara',
  'Wankaner',
  'Rajkot',
  'Halvad ',
  'Morena',
  'Morigaon',
  'Mulugu',
  'Mumbai',
  'Bombay Maharashtra',
  'Mumbai Suburban',
  'Mungeli',
  'Lormi',
  'Munger',
  'Murshidabad',
  'Muzaffarabad',
  'Muzaffarnagar',
  'Muzaffarpur',
  'Mysuru',
  'Nabarangapur',
  'Nadia',
  'Nagaon',
  'Nagapattinam',
  'Mayiladuthurai',
  'Nagapatnam',
  'Nagarkurnool',
  'Nagaur',
  'Nagpur',
  'Nainital',
  'Haldwani',
  'Lalkua',
  'Bhimtal',
  'Kaladhungi',
  'Ramnagar',
  'Nalanda',
  'Nalbari',
  'Nalgonda',
  'Namakkal',
  'Namsai',
  'Nanded',
  'Nandurbar',
  'Narayanpet',
  'Narayanpur',
  'Narayanpur Chhattisgarh',
  'Narmada',
  'Tilakwada',
  'Garudeshwar',
  'Nandod',
  'Dediyapada',
  'Sagbara.',
  'Narsimhapur',
  'Nashik',
  'Navsari',
  'Jalalpore',
  'Gandevi',
  'Chikhli',
  'Khergam',
  'Bansda',
  'Nawada',
  'Nayagarh',
  'Neemuch',
  'New Delhi',
  'Dilli',
  'Purani Dilli',
  'Old delhi',
  'Nicobars',
  'Carnicobar',
  'Campbell Bay',
  'Indira point',
  'Andaman and Nicobar Islands',
  'Nirmal',
  'Niwari',
  'Nizamabad',
  'Noney',
  'North 24 Parganas',
  '24 paraganas northWest Bengal',
  'North and Middle Andaman',
  'DiglipurAndaman and Nicobar Islands',
  'North Delhi',
  'Rohini',
  'Narela',
  'North District',
  'Sikkim North District',
  'Sikkim North',
  'North East Delhi',
  'Tahirpur',
  'Maujpur',
  'North Garo Hills',
  'North Goa',
  'Goa',
  'North Tripura',
  'North West Delhi',
  'Pitampura',
  'Shalimar Bagh',
  'Nuapada',
  'Ferozepur Jhirka',
  'Punahana',
  'Taoru',
  'Osmanabad',
  'Pakke Kessang',
  'Lemmi Arunachal Pradesh',
  'Pakur',
  'Palakkad',
  'Palamu',
  'Palghar',
  'Thane',
  'Vasai-Virar Palgarh',
  'Pali',
  'Panch Mahals',
  'Godhra',
  'Halol',
  'Jambughoda',
  'Shahera',
  'Morva Hadaf',
  'Goghamba',
  'panchmahal',
  'Panchkula',
  'KalkaHaryana',
  'Panipat',
  'SamalkhaHaryana',
  'Panna',
  'Papum Pare',
  'YupiaArunachal Pradesh',
  'Parbhani',
  'Paschim Bardhaman',
  'Pashchimi Singhbhum',
  'Sidhpur',
  'Harij',
  'Radhanpur',
  'Sami',
  'Shankeshwar',
  'Santalpur',
  'Sarasvati',
  'Chanasma',
  'Pathanamthitta',
  'Pathankot',
  'Patiala',
  'RajpuraPunjab',
  'Patna',
  'Pauri Garhwal',
  'Pauri',
  'Garhwal',
  'Kotdwara',
  'Dhumakot',
  'Peddapalli',
  'Perambalur',
  'Perumpuliur',
  'Perumpuliyur',
  'Peren',
  'Phek',
  'Pherzawl',
  'Pilibhit',
  'Pithoragarh',
  'Dharchhula',
  'Didihat',
  'Gangolihat',
  'Porbandar',
  'Ranavav',
  'Kutiyana',
  'Prakasam',
  'OngoleAndhra Pradesh',
  'Pratapgarh',
  'Prayagraj',
  'Allahabad',
  'Illahabad',
  'Prayag',
  'PondicherryPuducherry',
  'Pudukkottai',
  'Thondaiman seemai',
  'The New Fort',
  'Pulwama',
  'Punch',
  'Pune',
  'Pune City',
  'Pune Rural',
  'Purba Bardhaman',
  'Purbi Singhbhum',
  'JamshedpurJharkhand',
  'Puri',
  'Purnia',
  'Purulia',
  'puruliyaWest Bengal',
  'Rae Bareli',
  'RaebareliUttar Pradesh',
  'Raichur',
  'Raigarh',
  'Dadar',
  'Dharamjaigarh',
  'Gharghoda',
  'Kharsia',
  'Sarangarh',
  'Tamnar',
  'Tetla',
  'Alibag',
  'Alibaug',
  'Raipur',
  'Naya Raipur',
  'Abhanpur',
  'Arang',
  'Baikunth',
  'Banarsi',
  'Bhanpuri',
  'Bhatgaon',
  'Birgaon',
  'Gobranawapara',
  'Gogaon',
  'Mowa',
  'Rajim',
  'Simga',
  'Tilda Newra',
  'Urla',
  'Raisen',
  'Rajanna Sircilla',
  'SircillaTelangana',
  'Rajgarh',
  'Paddhari',
  'Lodhika',
  'Dhoraji',
  'Jam Kandorna',
  'Upleta',
  'Jetpur',
  'Kotda Sangani',
  'Jasdan',
  'Vinchhiya',
  'Gondal',
  'Rajnandgaon',
  'Ambagarh Chowki',
  'Chhuikhadan',
  'Dongargarh',
  'Dongergaon',
  'Gandai',
  'Khairagarh',
  'Rajouri',
  'Rajsamand',
  'Ramanagara',
  'Ramanathapuram',
  'RamanadTamil Nadu',
  'Ramban',
  'Ramgarh',
  'Rampur',
  'Ranchi',
  'Ranga Reddy',
  'Shamshabad Telangana',
  'Ratlam',
  'Ratnagiri',
  'Rayagada',
  'Reasi',
  'Rewa',
  'Rewari',
  'Kosli',
  'Bawal',
  'Ribhoi',
  'Rohtak',
  'Meham',
  'Rothasgarh',
  'Rohtas',
  'Rudraprayag',
  'Darmola',
  'Kedarnath',
  'Rupnagar',
  'S.A.S. Nagar',
  'Sahibzada Ajit Singh Nagar',
  'Mohali',
  'S.P.S. Nellore',
  'Sri Potti Sriramulu Nellore',
  'Nellore',
  'Sabar Kantha',
  'Himatnagar',
  'Idar',
  'Prantij',
  'Talod',
  'Khedbrahma',
  'Vadali',
  'Vijaynagar',
  'Poshina',
  'sabarkantha',
  'Sagar',
  'Saharanpur',
  'Saharsa',
  'Sahibganj',
  'Saiha',
  'Salem',
  'Samastipur',
  'Samba',
  'Sambalpur',
  'Sambhal',
  'Sangareddy',
  'Sangli',
  'Sangrur',
  'Sunam',
  'Malerkotla',
  'Sant Kabir Nagar',
  'Saraikela-Kharsawan',
  'Saran',
  'Satara',
  'MahabaleshwarMaharashtra',
  'Satna',
  'Madhya Pradesh',
  'Sawai Madhopur',
  'Sehore',
  'Senapati',
  'Seoni',
  'Serchhip',
  'Shahdara',
  'Yamuna ViharDelhi',
  'Shahdol',
  'Shahid Bhagat Singh Nagar',
  'Nawanshahr',
  'Shahjahanpur',
  'Shajapur',
  'Shamli',
  'Sheikhpura',
  'Sheohar',
  'Sheopur',
  'Shi Yomi',
  'TatoArunachal Pradesh',
  'Shimla',
  'Shivamogga',
  'ShimogaKarnataka',
  'Shivpuri',
  'Shrawasti',
  'Shupiyan',
  'Siang',
  'Boleng',
  'Pangin',
  'Siddharthnagar',
  'Siddipet',
  'Sidhi',
  'Sikar',
  'Simdega',
  'Sindhudurg',
  'Singrauli',
  'Sipahijala',
  'Sirmaur',
  'Sirohi',
  'Sirsa',
  'Dabwali',
  'Rania',
  'Kalanwali',
  'Ellenabad',
  'Sirsapattan',
  'Sitamarhi',
  'Sitapur',
  'Sivaganga',
  'Sivagangai SeemaiTamil Nadu',
  'Sivasagar',
  'Siwan',
  'Solan',
  'Solapur',
  'Sonbhadra',
  'Sonipat',
  'Ganaur',
  'Gohana',
  'Sonepat',
  'Sonitpur',
  'South 24 Parganas',
  '24 south parganasWest Bengal',
  'South Andaman',
  'Port Blair',
  'Andaman',
  'South Delhi',
  'Dhaulakuan',
  'Lado Sarai',
  'Chatarpur',
  'Pushp Vihar',
  'South District',
  'Sikkim South District',
  'Sikkim South',
  'South East Delhi',
  'Nizamuddin',
  'Lajpath Nagar',
  'Tuglakabad',
  'Badarpur',
  'South Ex',
  'Safdarjung',
  'South Garo Hills',
  'South Goa',
  'South Salmara Mancachar',
  'South Tripura',
  'South West Delhi',
  'Bijwasan',
  'Kapashera',
  'Palam',
  'Najafgarh',
  'South West Garo Hills',
  'South West Khasi Hills',
  'Sri Muktsar Sahib',
  'Muktsar',
  'Muktasar',
  'Srikakulam',
  'ChicacoleAndhra Pradesh',
  'Srinagar',
  'Subarnapur',
  'Sukma',
  'Chhindgarh',
  'Konta',
  'Sultanpur',
  'Sundargarh',
  'rourkela Odisha',
  'Jammu and Kashmir',
  'Supaul',
  'Surajpur',
  'Bishrampur',
  'Odagi',
  'Pratappur',
  'Prem Nagar',
  'Ramanuj Nagar',
  'Surat',
  'Surendranagar',
  'Wadhwan Gujarat',
  'Surguja',
  'Ambikapur',
  'Namna Kalan',
  'Phunderdihari',
  'Telgaon',
  'Suryapet',
  'Tamenglong',
  'Tapi',
  'Vyara',
  'Songadh',
  'Nijhar',
  'Valod',
  'Uchhal',
  'Dolavan',
  'Kukarmunda',
  'Tarn Taran',
  'Tawang',
  'Tehri Garhwal',
  'Ghanshali',
  'Deoprayag',
  'Tehri',
  'Dhanolti',
  'Tengnoupal',
  'Thanjavur',
  'Tanjore Tamil Nadu',
  'The Dangs',
  'Subir',
  'Waghal',
  'Ahwa',
  'dang',
  'The Nilgiris',
  'Nilgiri',
  'ooty',
  'Theni',
  'Thiruvallur',
  'Thiru evvul Tamil Nadu',
  'Thiruvananthapuram',
  'Thiruvarur',
  'Tiruvarur Tamil Nadu',
  'Thoothukkudi',
  'Tuticorin Tamil Nadu',
  'Thoubal',
  'Thrissur',
  'Tikamgarh',
  'Tamil Nadu',
  'Tinsukia',
  'Tirap',
  'Khonsa Arunachal Pradesh',
  'Tiruchirappalli',
  'Trichinopoly',
  'Trichy',
  'Tiruchi',
  'Tirunelveli',
  'Tenkasi Tamil Nadu',
  'Tiruppur',
  'Tirupur Tamil Nadu',
  'Tiruvannamalai',
  'Arunai Tamil Nadu',
  'Tonk',
  'Tuensang',
  'Tumakuru',
  'Udaipur',
  'Udalguri',
  'Udham Singh Nagar',
  'Rudrapur Uttarakhand',
  'Udhampur',
  'Udupi',
  'Ujjain',
  'Nagda',
  'Badnagar',
  'Ukhrul',
  'Umaria',
  'Unnao',
  'Unokoti',
  'Upper Dibang Valley',
  'AniniArunachal Pradesh',
  'Upper Siang',
  'YingkiongArunachal Pradesh',
  'Upper Subansiri',
  'DaporijoArunachal Pradesh',
  'Uttar Bastar Kanker',
  'Antagarh',
  'Charama',
  'Narharpur',
  'Pakhanjur',
  'Uttar Dinajpur',
  'Uttara Kannada',
  'Uttarkashi',
  'Purola',
  'Yamunotri',
  'Gangotri',
  'Vadodara',
  'Dabhoi',
  'Karjan',
  'Padra',
  'Savli',
  'Sinor',
  'Waghodia',
  'Vaishali',
  'Valsad',
  'Pardi',
  'Vapi',
  'Dharampur',
  'Kaparada',
  'Umbergaon',
  'Varanasi',
  'Banaras',
  'Benaras',
  'Kashi',
  'Vellore',
  'Vellur',
  'Vidisha',
  'Vijayapura',
  'Vikarabad',
  'Viluppuram',
  'Kallakurichi ',
  'Virudhunagar',
  'VirudupattiTamil Nadu',
  'Visakhapatnam',
  'VizagapatamAndhra Pradesh',
  'Vizianagaram',
  'VijayanagaramAndhra Pradesh',
  'Wanaparthy',
  'Warangal Rural',
  'GeesugondaTelangana',
  'Warangal Urban',
  'Warangal city',
  'warangal',
  'Wardha',
  'Washim',
  'Wayanad',
  'West Champaran',
  'West Delhi',
  'Punjabi Bagh',
  'Paschim Vihar',
  'Janakpuri',
  'Kirti Nagar',
  'West District',
  'Sikkim West District',
  'Sikkim West',
  'West Garo Hills',
  'West Godavari',
  'Paschima Godavari Jilla',
  'Eluru',
  'West Jaintia Hills',
  'West Kameng',
  'BomdilaArunachal Pradesh',
  'West Karbi Anglong',
  'West Khasi Hills',
  'West Siang',
  'Aalo',
  'Along',
  'West Tripura',
  'Wokha',
  'Y.S.R.',
  'Kadapa',
  'Cuddapah',
  'Yadadri Bhuvanagiri',
  'Bhongiri Telangana',
  'Yadgir',
  'Yamunanagar',
  'Jagadhri',
  'Chhachhrauli',
  'Sadhaura',
  'Adi Badri',
  'Radaur',
  'Yanam',
  'Yavatmal',
  'Zunheboto',
];

export const hints = {
  'hi-IN': commonHints,
  'en-IN': commonHints,
};
