const commonHints = [
  'active',
  'recovered',
  'deceased',
  'cases',
  'new',
  'so far',
  'confirmed',
  'active cases',
  'recovered cases',
  'deceased cases',
  'confirmed cases',
  'death',
  'died',
  'India',
  'Adilabad',
  'Telangana',
  'Agar Malwa',
  'Agra',
  'Uttar Pradesh',
  'Ahmadabad',
  'AmdavadGujarat',
  'Ahmadnagar',
  'Ahmednagar',
  'Maharashtra',
  'Aizawl',
  'Mizoram',
  'Ajmer',
  'Rajasthan',
  'Akola',
  'Maharashtra',
  'Alappuzha',
  'Kerala',
  'Aligarh',
  'Uttar Pradesh',
  'Alipurduar',
  'alipurdwar West Bengal',
  'Alirajpur',
  'Almora',
  'Dwarahat',
  'Ranikhet',
  'Someshwar',
  'Jageshwar',
  'Uttarakhand',
  'Alwar',
  'Rajasthan',
  'Ambala',
  'Mulana',
  'Naraingarh',
  'Haryana',
  'Ambedkar Nagar',
  'AkbarpurUttar Pradesh',
  'Amethi',
  'Uttar Pradesh',
  'Amravati',
  'Maharashtra',
  'Amreli',
  'Anumanji',
  'Amlik',
  'Amravat',
  'Gujarat',
  'Amritsar',
  'Punjab',
  'Amroha',
  'Jyotiba Phule Nagar',
  'Azizpura',
  'Uttar Pradesh',
  'Anand',
  'Khambhat',
  'Karamsad',
  'Tarapur',
  'Petlad',
  'Sojitra',
  'Gujarat',
  'Anantapur',
  'Anantapuramu',
  'Hindupur',
  'Andhra Pradesh',
  'Anantnag',
  'Anjaw',
  'Hawai Arunachal Pradesh',
  'Anugul',
  'Odisha',
  'Anuppur',

  'Araria',
  'Bihar',
  'Aravalli',
  'Aravalli',
  'Modasa',
  'Gujarat',
  'Ariyalur',
  'Arwal',
  'Bihar',
  'Ashoknagar',

  'Auraiya',
  'Kannauj',
  'Etawah',
  'Uttar Pradesh',
  'Aurangabad',
  'Bihar',
  'Aurangabad',
  'Maharashtra',
  'Azamgarh',
  'Azamgadh Uttar Pradesh',
  'Badgam',
  'Bagalkote',
  'Karnataka',
  'Bageshwar',
  'Uttarakhand',
  'Baghpat',
  'Uttar Pradesh',
  'Bahraich',
  'Uttar Pradesh',
  'Baksa',
  'Assam',
  'Balaghat',

  'Balangir',
  'Odisha',
  'Baleshwar',
  'Odisha',
  'Ballari',
  'Karnataka',
  'Ballia',
  'Uttar Pradesh',
  'Balod',
  'Dalli Rajhara Chhattisgarh',
  'Baloda Bazar',
  'Bhatapara Chhattisgarh',
  'Balrampur',
  'Kusmi',
  'Rajpur',
  'Ramanujganj',
  'Ramchandarpur',
  'Shankargarh',
  'Wadrafnagar',
  'Chhattisgarh',
  'Balrampur',
  'Uttar Pradesh',
  'Bametara',
  'Bametara',
  'Nawagarh',
  'Saja',
  'Chhattisgarh',
  'Banas Kantha',
  'banaskantha Gujarat',
  'Banda',
  'Uttar Pradesh',
  'Bandipore',
  'Banka',
  'Bihar',
  'Bankura',
  'West Bengal',
  'Banswara',
  'Rajasthan',
  'Bara Banki',
  'BarabankiUttar Pradesh',
  'Baramula',
  'Baran',
  'Rajasthan',
  'Bareilly',
  'Uttar Pradesh',
  'Bargarh',
  'Odisha',
  'Barmer',
  'Rajasthan',
  'Barnala',
  'Punjab',
  'Barpeta',
  'Assam',
  'Barwani',

  'Bastar',
  'Darba',
  'Frezarpur',
  'Hatkachora',
  'Jagdalpur',
  'Jagdalpur',
  'Sosanpal',
  'Chhattisgarh',
  'Basti',
  'Uttar Pradesh',
  'Bathinda',
  'Punjab',
  'Baudh',
  'Odisha',
  'Begusarai',
  'Bihar',
  'Belagavi',
  'Karnataka',
  'Bengaluru',
  'Karnataka',
  'Bengaluru Rural',
  'Karnataka',
  'Betul',

  'Bhadohi',
  'Uttar Pradesh',
  'Bhadradri Kothagudem',
  'Kothagudem Telangana',
  'Bhadrak',
  'Odisha',
  'Bhagalpur',
  'Bihar',
  'Bhandara',
  'Maharashtra',
  'Bharatpur',
  'Rajasthan',
  'Bharuch',
  'broach',
  'Amirgadh',
  'Bhabhar',
  'Dantiwada',
  'Danta',
  'Deesa',
  'Deodar',
  'Dhanera',
  'Palanpur',
  'Sihori',
  'Kankrej',
  'Tharad',
  'Vadgam',
  'Lakhni',
  'Suigam',
  'Vav',
  'Gujarat',
  'Bhavnagar',
  'Bhavnagar',
  'Sihor',
  'Umrala',
  'Gariadhar',
  'Palitana',
  'Mahuva',
  'Talaja',
  'Ghogha',
  'Jesar',
  'Vallbhipur.',
  'Gujarat',
  'Bhilwara',
  'Rajasthan',
  'Bhind',

  'Bhiwani',
  'Bhiwani',
  'Loharu',
  'Siwani',
  'Tosham',
  'Haryana',
  'Bhojpur',
  'ArrahBihar',
  'Bhopal',

  'Bid',
  'Beed',
  'Beed',
  'Maharashtra',
  'Bidar',
  'Karnataka',
  'Bijapur',
  'Bijapur',
  'Bhopalpatnam',
  'Chhattisgarh',
  'Bijnor',
  'Uttar Pradesh',
  'Bikaner',
  'Rajasthan',
  'Bilaspur',
  'Baitalpur',
  'Bilha',
  'Bodri',
  'Deori',
  'Gaurella',
  'Ghutku',
  'Kota',
  'Lingiyadih',
  'Mehmand',
  'Pendra',
  'Ratanpur',
  'Sirgiti',
  'Takhatpur',
  'Chhattisgarh',
  'Bilaspur',
  'Himachal Pradesh',
  'Birbhum',
  'West Bengal',
  'Bishnupur',
  'Manipur',
  'Biswanath',
  'Biswanath Chariali',
  'Assam',
  'Bokaro',
  'Jharkhand',
  'Bongaigaon',
  'Assam',
  'Botad',
  'Bitad',
  'Gadhada',
  'Barvala',
  'Ranpur',
  'Gujarat',
  'Budaun',
  'Uttar Pradesh',
  'Bulandshahr',
  'Bulandshahar',
  'Khurja',
  'Uttar Pradesh',
  'Buldana',
  'BuldhanaMaharashtra',
  'Bundi',
  'Rajasthan',
  'Burhanpur',

  'Buxar',
  'BalliaBihar',
  'Cachar',
  'Assam',
  'Central Delhi',
  'Cannaught Place',
  'CP',
  'Delhi',
  'Chamarajanagara',
  'Karnataka',
  'Chamba',
  'Himachal Pradesh',
  'Chamoli',
  'Badrinath',
  'Karnprayag',
  'Tharali',
  'Uttarakhand',
  'Champawat',
  'Uttarakhand',
  'Champhai',
  'Mizoram',
  'Chandauli',
  'Uttar Pradesh',
  'Chandel',
  'Manipur',
  'Chandigarh',
  'Chandigarh',
  'Chandrapur',
  'Maharashtra',
  'Changlang',
  'Arunachal Pradesh',
  'Charaideo',
  'Assam',
  'Charki Dadri',
  'BadhraHaryana',
  'Chatra',
  'Jharkhand',
  'Chennai',
  'Chhatarpur',

  'Chhindwara',

  'Chikkaballapura',
  'Karnataka',
  'Chikkamagaluru',
  'Karnataka',
  'Chirang',
  'Assam',
  'Chitradurga',
  'Karnataka',
  'Chitrakoot',
  'Uttar Pradesh',
  'Chittaurgarh',
  'Rajasthan',
  'Chittoor',
  'Andhra Pradesh',
  'Chota Udaipur',
  'Chhota Udepur',
  'Pavi Jetpur',
  'Kawant',
  'Naswadi',
  'Sankheda',
  'Bodeli',
  'Gujarat',
  'Churachandpur',
  'Manipur',
  'Churu',
  'Rajasthan',
  'Coimbatore',
  'Cooch Behar',
  'Coochbehar',
  'Koch Bihar',
  'West Bengal',
  'Cuddalore',
  'Cuttack',
  'Odisha',
  'Dadra and Nagar Haveli',
  'Dakshin Bastar Dantewada',
  'Bade Bacheli',
  'Dantewada',
  'Geedam',
  'Katekalyan',
  'Kirandul',
  'Kuwakonda',
  'Penta',
  'Chhattisgarh',
  'Dakshin Dinajpur',
  'South DinajpurWest Bengal',
  'Dakshina Kannada',
  'Karnataka',
  'Daman',
  'Daman And Diu',
  'Damoh',

  'Darbhanga',
  'Bihar',
  'Darjeeling',
  'West Bengal',
  'Darrang',
  'Assam',
  'Datia',

  'Dausa',
  'Rajasthan',
  'Davanagere',
  'Karnataka',
  'Debagarh',
  'Odisha',
  'Dehradun',
  'Mussoorie',
  'Rishikesh',
  'Uttarakhand',
  'Deoghar',
  'Jharkhand',
  'Deoria',
  'Uttar Pradesh',
  'Devbhumi Dwarka',
  'Dwarka',
  'Bhanvad',
  'Kalyanpur',
  'Khambaila',
  'Gujarat',
  'Dewas',

  'Dhalai',
  'Tripura',
  'Dhamtari',
  'Bagoud',
  ' Kurud',
  'Nagri',
  'Dhamtari',
  'Chhattisgarh',
  'Dhanbad',
  'Jharkhand',
  'Dhar',
  'PithampurMadhya Pradesh',
  'Dharmapuri',
  'dharmapuriTamil Nadu',
  'Dharwad',
  'Karnataka',
  'Dhaulpur',
  'Rajasthan',
  'Dhemaji',
  'Assam',
  'Dhenkanal',
  'Odisha',
  'Dhubri',
  'Assam',
  'Dhule',
  'Maharashtra',
  'Dibrugarh',
  'Assam',
  'Dima Hasao',
  'Assam',
  'Dimapur',
  'Nagaland',
  'Dindigul',
  'Dindori',

  'Diu',
  'Daman And Diu',
  'Doda',
  'Dohad',
  'Dahod',
  'Jhalod',
  'Devgarh',
  'Garbada',
  'Limkheda',
  'Fatehpur',
  'Dhanpur',
  'Sanjeli',
  'Gujarat',
  'Dumka',
  'Jharkhand',
  'Dungarpur',
  'Rajasthan',
  'Durg',
  'Bhilai',
  ' Durg',
  ' Ahiwara',
  'Bhilai Charoda',
  'Dhamdha',
  'Jamul',
  'Khamhria',
  'Kumhari',
  'Mahamaya',
  'Parpodi',
  'Patan',
  'Chhattisgarh',
  'East Champaran',
  'Bihar',
  'East Delhi',
  'Dilshad Garden',
  'Mayur vihar',
  'Parpatganj',
  'Delhi',
  'East District',
  'Sikkim East District',
  'Sikkim East',
  'Sikkim',
  'East Garo Hills',
  'Meghalaya',
  'East Godavari',
  'KakinadaAndhra Pradesh',
  'East Jaintia Hills',
  'Meghalaya',
  'East Kameng',
  'SeppaArunachal Pradesh',
  'East Khasi Hills',
  'Meghalaya',
  'East Siang',
  'PasighatArunachal Pradesh',
  'Ernakulam',
  'Kerala',
  'Erode',
  'Etah',
  'Uttar Pradesh',
  'Etawah',
  'Uttar Pradesh',
  'Faizabad',
  'AyodhyaUttar Pradesh',
  'Faridabad',
  'Nuh',
  'Palwal',
  'Haryana',
  'Faridkot',
  'Punjab',
  'Farrukhabad',
  'FategarhUttar Pradesh',
  'Fatehabad',
  'Ratia',
  'Tohana',
  'Haryana',
  'Fatehgarh Sahib',
  'Punjab',
  'Fatehpur',
  'Uttar Pradesh',
  'Fazilka',
  'AboharPunjab',
  'Firozabad',
  'ShikohabadUttar Pradesh',
  'Firozpur',
  'Punjab',
  'Gadag',
  'Karnataka',
  'Gadchiroli',
  'Maharashtra',
  'Gajapati',
  'Odisha',
  'Ganderbal',
  'Gandhinagar',
  'Motera',
  'Adala',
  'Kalol INA',
  'Dahegam',
  'Mansa',
  'Gujarat',
  'Ganganagar',
  'Rajasthan',
  'Ganjam',
  'BerhampurOdisha',
  'Garhwa',
  'Jharkhand',
  'Gariaband',
  'Gariaband Chhattisgarh',
  'Gautam Buddha Nagar',
  'Noida',
  'Greater Noida',
  'Uttar Pradesh',
  'Gaya',
  'Bihar',
  'Ghaziabad',
  'ModinagarUttar Pradesh',
  'Ghazipur',
  'Uttar Pradesh',
  'Gir Somnath',
  'Veraval',
  'Talala',
  'Sutrapada',
  'Kodinar',
  'Una',
  'Gir-Gadhada',
  'Gujarat',
  'Giridih',
  'Jharkhand',
  'Goalpara',
  'Assam',
  'Godda',
  'Jharkhand',
  'Golaghat',
  'Assam',
  'Gomati',
  'Tripura',
  'Gonda',
  'Uttar Pradesh',
  'Gondiya',
  'GondiaMaharashtra',
  'Gopalganj',
  'Bihar',
  'Gorakhpur',
  'Uttar Pradesh',
  'Gumla',
  'Jharkhand',
  'Guna',

  'Guntur',
  'Andhra Pradesh',
  'Gurdaspur',
  'BatalaPunjab',
  'Gurugram',
  'Sohna',
  'Pataudi',
  'Farukh Nagar',
  'Manesar',
  'gurgaon',
  'Haryana',
  'Gwalior',

  'Hailakandi',
  'Assam',
  'Hamirpur',
  'Himachal Pradesh',
  'Hamirpur',
  'Uttar Pradesh',
  'Hanumangarh',
  'Rajasthan',
  'Hapur',
  'Uttar Pradesh',
  'Harda',

  'Hardoi',
  'Uttar Pradesh',
  'Haridwar',
  'Roorkee Uttarakhand',
  'Hassan',
  'Karnataka',
  'Hathras',
  'Uttar Pradesh',
  'Haveri',
  'Karnataka',
  'Hazaribagh',
  'Jharkhand',
  'Hingoli',
  'Maharashtra',
  'Hisar',
  'Adampur',
  'Agroha',
  'Barwala',
  'Hansi',
  'Narnaund',
  'Uklanamandi',
  'Haryana',
  'Hojai',
  'Assam',
  'Hooghly',
  'Hoogli',
  'Hugli',
  'West Bengal',
  'Hoshangabad',
  'ItarsiMadhya Pradesh',
  'Hoshiarpur',
  'Punjab',
  'Howrah',
  'West Bengal',
  'Hyderabad',
  'Telangana',
  'Idukki',
  'Kerala',
  'Imphal East',
  'Manipur',
  'Imphal West',
  'Manipur',
  'Indore',

  'Jabalpur',

  'Jagatsinghapur',
  'Odisha',
  'Jagitial',
  'Telangana',
  'Jaipur',
  'Rajasthan',
  'Jaisalmer',
  'Rajasthan',
  'Jajapur',
  'Odisha',
  'Jalandhar',
  'Punjab',
  'Jalaun',
  'OraiUttar Pradesh',
  'Jalgaon',
  'BhusawalMaharashtra',
  'Jalna',
  'Maharashtra',
  'Jalore',
  'Rajasthan',
  'Jalpaiguri',
  'West Bengal',
  'Jammu',
  'Jamnagar',
  'Jam Jodhpur',
  'Jodiya',
  'DhrolJamnagar',
  'Lalpur',
  'Kalavad',
  'Gujarat',
  'Jamtara',
  'Jharkhand',
  'Jamui',
  'Bihar',
  'Jangoan',
  'Telangana',
  'Janjgir Champa',
  'Adbhar',
  'Akaltara',
  'Baloda',
  'Champa',
  'Janjgir',
  'Kharod',
  'Naila-Janjgir',
  'Naya Baradwar',
  'Pamgarh',
  'Sakti',
  'Shivrinarayan',
  'Chhattisgarh',
  'Jashpur',
  'Jashpur Nagar',
  'Kunkuri',
  'Pathalgaon',
  'Chhattisgarh',
  'Jaunpur',
  'Uttar Pradesh',
  'Jayashankar',
  'Bhupalpalle',
  'Jayashankar Bhupalpally',
  'Telangana',
  'Jehanabad',
  'Bihar',
  'Jhabua',

  'Jhajjar',
  'Bahadurgarh',
  'Badli',
  'Beri',
  'Haryana',
  'Jhalawar',
  'Rajasthan',
  'Jhansi',
  'Uttar Pradesh',
  'Jhargram',
  'West Bengal',
  'Jharsuguda',
  'Odisha',
  'Jhunjhunu',
  'Rajasthan',
  'Jind',
  'Narwana',
  'Safidon',
  'Haryana',
  'Jiribam',
  'Manipur',
  'Jodhpur',
  'Rajasthan',
  'Jogulamba Gadwal',
  'Gadwal Telangana',
  'Jorhat',
  'Assam',
  'Junagadh',
  'Junagadh',
  'Bhesan',
  'Junagadhl',
  'Keshod',
  'Malia',
  'Manavadar',
  'Mangrol',
  'Mendarda',
  'Vanthali',
  'Visavadar',
  'Gujarat',
  'Kabeerdham',
  'Kabirdham',
  'Chilpi',
  'Kawardha',
  'Pandariya',
  'Pandatarai',
  'Chhattisgarh',
  'Kachchh',
  'Abdasa',
  'Anjar',
  'Bhachau',
  'Bhuj',
  'Gandhidham',
  'Lakhpat',
  'Mandvi',
  'Mundra',
  'Nakhatrana',
  'Rapar',
  'Gujarat',
  'Kaimur Bhabua',
  'Bihar',
  'Kaithal',
  'Guhla',
  'Pundri',
  'Kalayat',
  'Haryana',
  'Kakching',
  'Manipur',
  'Kalaburagi',
  'Gulbarga Karnataka',
  'Kalahandi',
  'bhawanipatna Odisha',
  'Kalimpong',
  'West Bengal',
  'Kamareddy',
  'Telangana',
  'Kamjong',
  'Manipur',
  'Kamle',
  'Khamle',
  'Raga',
  'Arunachal Pradesh',
  'Kamrup',
  'Assam',
  'Kamrup Metropolitan',
  'Guwahati Assam',
  'Kancheepuram',
  'Kanchipuram Tamil Nadu',
  'Kandhamal',
  'Odisha',
  'Kangpokpi',
  'Manipur',
  'Kangra',
  'Himachal Pradesh',
  'Kanker',
  'Bhanupratappur',
  'Kapsi',
  'Pakhanjore',
  'Kannauj',
  'Uttar Pradesh',
  'Kanniyakumari',
  'Kanyakumari Tamil Nadu',
  'Kannur',
  'Kerala',
  'Kanpur Dehat',
  'Uttar Pradesh',
  'Kanpur Nagar',
  'Kanpur city',
  'Kanpur',
  'Uttar Pradesh',
  'Kapurthala',
  'Phagwara Punjab',
  'Karaikal',
  'Puducherry',
  'Karauli',
  'Rajasthan',
  'Karbi Anglong',
  'Assam',
  'Kargil',
  'Ladakh',
  'Karimganj',
  'Assam',
  'Karimnagar',
  'Telangana',
  'Karnal',
  'Nilokheri',
  'Indri',
  'Gharaunda',
  'Assandh',
  'Haryana',
  'Karur',
  'Kasaragod',
  'Kerala',
  'Kasganj',
  'Uttar Pradesh',
  'Kathua',
  'Katihar',
  'Bihar',
  'Katni',
  'Murwara Madhya Pradesh',
  'Kaushambi',
  'Uttar Pradesh',
  'Kendrapara',
  'Odisha',
  'Kendujhar',
  'Odisha',
  'Khagaria',
  'Bihar',
  'Khammam',
  'Telangana',
  'Khandwa',
  'East Nimar Madhya Pradesh',
  'Khargone',
  'West Nimar Madhya Pradesh',
  'Kheda',
  'Nadiad',
  'Thasra',
  'Kapadvanj',
  'Mehmedabad',
  'Kathlal',
  'Matar',
  'Mahudha',
  'Kaira',
  'Gujarat',
  'Kheri',
  'Lakhimpur Kheri Uttar Pradesh',
  'Khordha',
  'Bhubhaneshwar Odisha',
  'Khowai',
  'Tripura',
  'Khunti',
  'Jharkhand',
  'Kinnaur',
  'Himachal Pradesh',
  'Kiphire',
  'Nagaland',
  'Kishanganj',
  'Bihar',
  'Kishtwar',
  'Kodagu',
  'coorg Karnataka',
  'Kodarma',
  'Jharkhand',
  'Kohima',
  'Nagaland',
  'Kokrajhar',
  'Assam',
  'Kolar',
  'Karnataka',
  'Kolasib',
  'Mizoram',
  'Kolhapur',
  'Maharashtra',
  'Kolkata',
  'Calcutta West Bengal',
  'Kollam',
  'Kerala',
  'Kondagaon',
  'Keskal',
  'Pharasgaon',
  'Chhattisgarh',
  'Koppal',
  'Karnataka',
  'Koraput',
  'Odisha',
  'Korba',
  'Banki Mongra',
  'Dipka',
  'Katghora',
  'Korba',
  'Rajgamar',
  'Chhattisgarh',
  'Koriya',
  'Baikunthpur',
  'Koriya',
  'Chharchha',
  'Chirmiri',
  'Jhagrakhand',
  'Khongapani',
  'Manendragarh',
  'Chhattisgarh',
  'Kota',
  'Rajasthan',
  'Kottayam',
  'Kerala',
  'Kozhikode',
  'Kerala',
  'Kra Daadi',
  'New Palin',
  'Jamin',
  'Arunachal Pradesh',
  'Krishna',
  'Vijayawada',
  'Machilipatnam',
  'Andhra Pradesh',
  'Krishnagiri',
  'Kulgam',
  'Kullu',
  'Himachal Pradesh',
  'Kumuram Bheem Asifabad',
  'Asifabad Telangana',
  'Kupwara',
  'Kurnool',
  'Andhra Pradesh',
  'Kurukshetra',
  'Thanesar',
  'Pehowa',
  'Haryana',
  'Kurung Kumey',
  'Koloriang Arunachal Pradesh',
  'Kushinagar',
  'Uttar Pradesh',
  'Lahul and Spiti',
  'Himachal Pradesh',
  'Lakhimpur',
  'Assam',
  'Lakhisarai',
  'Bihar',
  'Lakshadweep',
  'Lakshadweep',
  'Lalitpur',
  'Uttar Pradesh',
  'Latehar',
  'Jharkhand',
  'Latur',
  'Maharashtra',
  'Lawngtlai',
  'Mizoram',
  'Leh',
  'Ladakh',
  'Lepa Rada',
  'Basar Arunachal Pradesh',
  'Lohardaga',
  'Jharkhand',
  'Lohit',
  'Tezu Arunachal Pradesh',
  'Longding',
  'Arunachal Pradesh',
  'Longleng',
  'Nagaland',
  'Lower Dibang Valley',
  'Roing Arunachal Pradesh',
  'Lower Siang',
  'LikabaliArunachal Pradesh',
  'Lower Subansiri',
  'ZiroArunachal Pradesh',
  'Lucknow',
  'Uttar Pradesh',
  'Ludhiana',
  'Punjab',
  'Lunglei',
  'Mizoram',
  'Madhepura',
  'Bihar',
  'Madhubani',
  'Bihar',
  'Madurai',
  'Mahabubabad',
  'Telangana',
  'Mahabubnagar',
  'Telangana',
  'Mahasamund',
  'Bagbahara',
  'Basna',
  'Mahasamund',
  'Pithora',
  'Saraipali',
  'Sirpur',
  'Chhattisgarh',
  'Mahe',
  'Puducherry',
  'Mahendragarh',
  'Narnaul',
  'Nangal Chowdhary',
  'Kanina Mahendragarh',
  'Ateli',
  'Haryana',
  'Mahesana',
  'Vijapur',
  'Bahucharaji',
  'Satlasana',
  'Modhera',
  'Unjha',
  'Vadnagar',
  'Kalol',
  'Kadi',
  'Visnagar',
  'Kherva',
  'Jotana',
  'Kheralu',
  'Gujarat',
  'Mahisagar',
  'Balasinor',
  'Lunavada',
  'Kadana',
  'Virpur',
  'Santrampur',
  'Khanpur',
  'Gujarat',
  'Mahoba',
  'Uttar Pradesh',
  'Mahrajganj',
  'Uttar Pradesh',
  'Mainpuri',
  'Uttar Pradesh',
  'Majuli',
  'Assam',
  'Malappuram',
  'Kerala',
  'Maldah',
  'Malda',
  'Maldaha',
  'West Bengal',
  'Malkangiri',
  'Odisha',
  'Mamit',
  'Mizoram',
  'Mancherial',
  'Telangana',
  'Mandi',
  'Himachal Pradesh',
  'Mandla',

  'Mandsaur',

  'Mandya',
  'Karnataka',
  'Mansa',
  'Punjab',
  'Mathura',
  'Vrindavan',
  'Mathura Vrindavan',
  'Uttar Pradesh',
  'Mau',
  'Uttar Pradesh',
  'Mayurbhanj',
  'baripada Odisha',
  'Medak',
  'Telangana',
  'Medchal Malkajgiri',
  'Telangana',
  'Medinipur East',
  'Purba Medinipur',
  'East Medinipur',
  'East Midnapore',
  'Midnapore East',
  'West Bengal',
  'Medinipur West',
  'Paschim Medinipur',
  'West Midnapore',
  'Midnapore West',
  'West Bengal',
  'Meerut',
  'Uttar Pradesh',
  'Mirpur',
  'Mirzapur',
  'Uttar Pradesh',
  'Moga',
  'Punjab',
  'Mokokchung',
  'Nagaland',
  'Mon',
  'Nagaland',
  'Moradabad',
  'Uttar Pradesh',
  'Morbi',
  'Maliya',
  'Tankara',
  'Wankaner',
  'Rajkot',
  'Halvad ',
  'Gujarat',
  'Morena',

  'Morigaon',
  'Assam',
  'Mulugu',
  'Telangana',
  'Mumbai',
  'BombayMaharashtra',
  'Mumbai Suburban',
  'Maharashtra',
  'Mungeli',
  'Lormi',
  'Mungeli',
  'Chhattisgarh',
  'Munger',
  'Bihar',
  'Murshidabad',
  'West Bengal',
  'Muzaffarabad',
  'Muzaffarnagar',
  'Uttar Pradesh',
  'Muzaffarpur',
  'Bihar',
  'Mysuru',
  'Karnataka',
  'Nabarangapur',
  'Odisha',
  'Nadia',
  'West Bengal',
  'Nagaon',
  'Assam',
  'Nagapattinam',
  'Mayiladuthurai',
  'Nagapatnam',
  'Nagarkurnool',
  'Telangana',
  'Nagaur',
  'Rajasthan',
  'Nagpur',
  'Maharashtra',
  'Nainital',
  'Haldwani',
  'Lalkua',
  'Bhimtal',
  'Kaladhungi',
  'Ramnagar',
  'Uttarakhand',
  'Nalanda',
  'Bihar',
  'Nalbari',
  'Assam',
  'Nalgonda',
  'Telangana',
  'Namakkal',
  'Namsai',
  'Arunachal Pradesh',
  'Nanded',
  'Maharashtra',
  'Nandurbar',
  'Maharashtra',
  'Narayanpet',
  'Telangana',
  'Narayanpur',
  'Narayanpur Chhattisgarh',
  'Narmada',
  'Tilakwada',
  'Garudeshwar',
  'Nandod',
  'Dediyapada',
  'Sagbara.',
  'Gujarat',
  'Narsimhapur',

  'Nashik',
  'Maharashtra',
  'Navsari',
  'Jalalpore',
  'Gandevi',
  'Chikhli',
  'Khergam',
  'Bansda',
  'Gujarat',
  'Nawada',
  'Bihar',
  'Nayagarh',
  'Odisha',
  'Neemuch',

  'New Delhi',
  'Delhi',
  'Dilli',
  'Purani Dilli',
  'Old delhi',
  'Delhi',
  'Nicobars',
  'Carnicobar',
  'Campbell Bay',
  'Indira point',
  'Andaman and Nicobar Islands',
  'Nirmal',
  'Telangana',
  'Niwari',

  'Nizamabad',
  'Telangana',
  'Noney',
  'Manipur',
  'North 24 Parganas',
  '24 paraganas northWest Bengal',
  'North and Middle Andaman',
  'DiglipurAndaman and Nicobar Islands',
  'North Delhi',
  'Rohini',
  'Narela',
  'Delhi',
  'North District',
  'Sikkim North District',
  'Sikkim North',
  'Sikkim',
  'North East Delhi',
  'Tahirpur',
  'Maujpur',
  'Delhi',
  'North Garo Hills',
  'Meghalaya',
  'North Goa',
  'Goa',
  'North Tripura',
  'Tripura',
  'North West Delhi',
  'Pitampura',
  'Shalimar Bagh',
  'Delhi',
  'Nuapada',
  'Odisha',
  'Nuh',
  'Ferozepur Jhirka',
  'Punahana',
  'Taoru',
  'Haryana',
  'Osmanabad',
  'Maharashtra',
  'Pakke Kessang',
  'Lemmi Arunachal Pradesh',
  'Pakur',
  'Jharkhand',
  'Palakkad',
  'Kerala',
  'Palamu',
  'Jharkhand',
  'Palghar',
  'Thane',
  'Vasai-Virar Palgarh',
  'Maharashtra',
  'Pali',
  'Rajasthan',
  'Palwal',
  'Haryana',
  'Panch Mahals',
  'Godhra',
  'Halol',
  'Kalol',
  'Jambughoda',
  'Shahera',
  'Morva Hadaf',
  'Goghamba',
  'panchmahal',
  'Gujarat',
  'Panchkula',
  'KalkaHaryana',
  'Panipat',
  'SamalkhaHaryana',
  'Panna',

  'Papum Pare',
  'YupiaArunachal Pradesh',
  'Parbhani',
  'Maharashtra',
  'Paschim Bardhaman',
  'West Bengal',
  'Pashchimi Singhbhum',
  'Jharkhand',
  'Patan',
  'Sidhpur',
  'Harij',
  'Radhanpur',
  'Sami',
  'Shankeshwar',
  'Santalpur',
  'Sarasvati',
  'Chanasma',
  'Gujarat',
  'Pathanamthitta',
  'Kerala',
  'Pathankot',
  'Punjab',
  'Patiala',
  'RajpuraPunjab',
  'Patna',
  'Bihar',
  'Pauri Garhwal',
  'Pauri',
  'Garhwal',
  'Kotdwara',
  'Dhumakot',
  'Uttarakhand',
  'Peddapalli',
  'Telangana',
  'Perambalur',
  'Perambalur',
  'Perumpuliur',
  'Perumpuliyur',
  'Peren',
  'Nagaland',
  'Phek',
  'Nagaland',
  'Pherzawl',
  'Manipur',
  'Pilibhit',
  'Uttar Pradesh',
  'Pithoragarh',
  'Dharchhula',
  'Didihat',
  'Gangolihat',
  'Uttarakhand',
  'Porbandar',
  'Ranavav',
  'Kutiyana',
  'Gujarat',
  'Prakasam',
  'OngoleAndhra Pradesh',
  'Pratapgarh',
  'Rajasthan',
  'Pratapgarh',
  'Uttar Pradesh',
  'Prayagraj',
  'Allahabad',
  'Illahabad',
  'Prayag',
  'Uttar Pradesh',
  'Puducherry',
  'PondicherryPuducherry',
  'Pudukkottai',
  'Thondaiman seemai',
  'The New Fort',
  'Pulwama',
  'Punch',
  'Pune',
  'Pune City',
  'Pune Rural',
  'Maharashtra',
  'Purba Bardhaman',
  'West Bengal',
  'Purbi Singhbhum',
  'JamshedpurJharkhand',
  'Puri',
  'Odisha',
  'Purnia',
  'Bihar',
  'Purulia',
  'puruliyaWest Bengal',
  'Rae Bareli',
  'RaebareliUttar Pradesh',
  'Raichur',
  'Karnataka',
  'Raigarh',
  'Dadar',
  'Dharamjaigarh',
  'Gharghoda',
  'Kharsia',
  'Raigarh',
  'Sarangarh',
  'Tamnar',
  'Tetla',
  'Chhattisgarh',
  'Raigarh',
  'Alibag',
  'Alibaug',
  'Maharashtra',
  'Raipur',
  'Naya Raipur',
  'Abhanpur',
  'Arang',
  'Baikunth',
  'Banarsi',
  'Bhanpuri',
  'Bhatgaon',
  'Birgaon',
  'Gobranawapara',
  'Gogaon',
  'Mowa',
  'Raipur',
  'Rajim',
  'Simga',
  'Tilda Newra',
  'Urla',
  'Chhattisgarh',
  'Raisen',

  'Rajanna Sircilla',
  'SircillaTelangana',
  'Rajgarh',

  'Rajkot',
  'Paddhari',
  'Lodhika',
  'Dhoraji',
  'Rajkot',
  'Jam Kandorna',
  'Upleta',
  'Jetpur',
  'Kotda Sangani',
  'Jasdan',
  'Vinchhiya',
  'Gondal',
  'Gujarat',
  'Rajnandgaon',
  'Ambagarh Chowki',
  'Chhuikhadan',
  'Dongargarh',
  'Dongergaon',
  'Gandai',
  'Khairagarh',
  'Rajnandgaon',
  'Chhattisgarh',
  'Rajouri',
  'Rajsamand',
  'Rajasthan',
  'Ramanagara',
  'Karnataka',
  'Ramanathapuram',
  'RamanadTamil Nadu',
  'Ramban',
  'Ramgarh',
  'Jharkhand',
  'Rampur',
  'Uttar Pradesh',
  'Ranchi',
  'Jharkhand',
  'Ranga Reddy',
  'Shamshabad Telangana',
  'Ratlam',

  'Ratnagiri',
  'Maharashtra',
  'Rayagada',
  'Odisha',
  'Reasi',
  'Rewa',
  'Rewari',
  'Kosli',
  'Bawal',
  'Haryana',
  'Ribhoi',
  'Meghalaya',
  'Rohtak',
  'Meham',
  'Rothasgarh',
  'Haryana',
  'Rohtas',
  'Bihar',
  'Rudraprayag',
  'Darmola',
  'Kedarnath',
  'Uttarakhand',
  'Rupnagar',
  'Punjab',
  'S.A.S. Nagar',
  'Sahibzada Ajit Singh Nagar',
  'Mohali',
  'Punjab',
  'S.P.S. Nellore',
  'Sri Potti Sriramulu Nellore',
  'Nellore',
  'Andhra Pradesh',
  'Sabar Kantha',
  'Himatnagar',
  'Idar',
  'Prantij',
  'Talod',
  'Khedbrahma',
  'Vadali',
  'Vijaynagar',
  'Poshina',
  'sabarkantha',
  'Gujarat',
  'Sagar',

  'Saharanpur',
  'Uttar Pradesh',
  'Saharsa',
  'Bihar',
  'Sahibganj',
  'Jharkhand',
  'Saiha',
  'Mizoram',
  'Salem',
  'Samastipur',
  'Bihar',
  'Samba',
  'Sambalpur',
  'Odisha',
  'Sambhal',
  'Uttar Pradesh',
  'Sangareddy',
  'Telangana',
  'Sangli',
  'Maharashtra',
  'Sangrur',
  'Sunam',
  'Malerkotla',
  'Punjab',
  'Sant Kabir Nagar',
  'Uttar Pradesh',
  'Saraikela-Kharsawan',
  'Jharkhand',
  'Saran',
  'Bihar',
  'Satara',
  'MahabaleshwarMaharashtra',
  'Satna',
  'Madhya Pradesh',
  'Sawai Madhopur',
  'Rajasthan',
  'Sehore',

  'Senapati',
  'Manipur',
  'Seoni',

  'Serchhip',
  'Mizoram',
  'Shahdara',
  'Yamuna ViharDelhi',
  'Shahdol',

  'Shahid Bhagat Singh Nagar',
  'Nawanshahr',
  'Punjab',
  'Shahjahanpur',
  'Uttar Pradesh',
  'Shajapur',

  'Shamli',
  'Uttar Pradesh',
  'Sheikhpura',
  'Bihar',
  'Sheohar',
  'Bihar',
  'Sheopur',

  'Shi Yomi',
  'TatoArunachal Pradesh',
  'Shimla',
  'Himachal Pradesh',
  'Shivamogga',
  'ShimogaKarnataka',
  'Shivpuri',

  'Shrawasti',
  'Uttar Pradesh',
  'Shupiyan',
  'Siang',
  'Boleng',
  'Pangin',
  'Arunachal Pradesh',
  'Siddharthnagar',
  'Uttar Pradesh',
  'Siddipet',
  'Telangana',
  'Sidhi',

  'Sikar',
  'Rajasthan',
  'Simdega',
  'Jharkhand',
  'Sindhudurg',
  'Maharashtra',
  'Singrauli',

  'Sipahijala',
  'Tripura',
  'Sirmaur',
  'Himachal Pradesh',
  'Sirohi',
  'Rajasthan',
  'Sirsa',
  'Dabwali',
  'Rania',
  'Kalanwali',
  'Ellenabad',
  'Sirsapattan',
  'Haryana',
  'Sitamarhi',
  'Bihar',
  'Sitapur',
  'Uttar Pradesh',
  'Sivaganga',
  'Sivagangai SeemaiTamil Nadu',
  'Sivasagar',
  'Assam',
  'Siwan',
  'Bihar',
  'Solan',
  'Himachal Pradesh',
  'Solapur',
  'Maharashtra',
  'Sonbhadra',
  'Uttar Pradesh',
  'Sonipat',
  'Ganaur',
  'Gohana',
  'Sonepat',
  'Haryana',
  'Sonitpur',
  'Assam',
  'South 24 Parganas',
  '24 south parganasWest Bengal',
  'South Andaman',
  'Port Blair',
  'Andaman',
  'Andaman and Nicobar Islands',
  'South Delhi',
  'Dhaulakuan',
  'Lado Sarai',
  'Chatarpur',
  'Pushp Vihar',
  'Delhi',
  'South District',
  'Sikkim South District',
  'Sikkim South',
  'Sikkim',
  'South East Delhi',
  'Nizamuddin',
  'Lajpath Nagar',
  'Tuglakabad',
  'Badarpur',
  'South Ex',
  'Safdarjung',
  'Delhi',
  'South Garo Hills',
  'Meghalaya',
  'South Goa',
  'Goa',
  'South Salmara Mancachar',
  'Assam',
  'South Tripura',
  'Tripura',
  'South West Delhi',
  'Bijwasan',
  'Kapashera',
  'Palam',
  'Najafgarh',
  'Delhi',
  'South West Garo Hills',
  'Meghalaya',
  'South West Khasi Hills',
  'Meghalaya',
  'Sri Muktsar Sahib',
  'Muktsar',
  'Muktasar',
  'Punjab',
  'Srikakulam',
  'ChicacoleAndhra Pradesh',
  'Srinagar',
  'Subarnapur',
  'Odisha',
  'Sukma',
  'Chhindgarh',
  'Konta',
  'Sukma',
  'Chhattisgarh',
  'Sultanpur',
  'Uttar Pradesh',
  'Sundargarh',
  'rourkela Odisha',
  'Jammu and Kashmir',
  'Supaul',
  'Bihar',
  'Surajpur',
  'Bishrampur',
  'Odagi',
  'Pratappur',
  'Prem Nagar',
  'Ramanuj Nagar',
  'Surajpur',
  'Chhattisgarh',
  'Surat',
  'Gujarat',
  'Surendranagar',
  'Wadhwan Gujarat',
  'Surguja',
  'Ambikapur',
  'Namna Kalan',
  'Phunderdihari',
  'Sitapur',
  'Telgaon',
  'Chhattisgarh',
  'Suryapet',
  'Telangana',
  'Tamenglong',
  'Manipur',
  'Tapi',
  'Vyara',
  'Songadh',
  'Nijhar',
  'Valod',
  'Uchhal',
  'Dolavan',
  'Kukarmunda',
  'Gujarat',
  'Tarn Taran',
  'Punjab',
  'Tawang',
  'Arunachal Pradesh',
  'Tehri Garhwal',
  'Ghanshali',
  'Deoprayag',
  'Tehri',
  'Dhanolti',
  'Uttarakhand',
  'Tengnoupal',
  'Manipur',
  'Thane',
  'Maharashtra',
  'Thanjavur',
  'Tanjore Tamil Nadu',
  'The Dangs',
  'Subir',
  'Waghal',
  'Ahwa',
  'dang',
  'Gujarat',
  'The Nilgiris',
  'Nilgiri',
  'ooty',
  'Theni',
  'Thiruvallur',
  'Thiru evvul Tamil Nadu',
  'Thiruvananthapuram',
  'Kerala',
  'Thiruvarur',
  'Tiruvarur Tamil Nadu',
  'Thoothukkudi',
  'Tuticorin Tamil Nadu',
  'Thoubal',
  'Manipur',
  'Thrissur',
  'Kerala',
  'Tikamgarh',
  'Tamil Nadu',
  'Tinsukia',
  'Assam',
  'Tirap',
  'Khonsa Arunachal Pradesh',
  'Tiruchirappalli',
  'Trichinopoly',
  'Trichy',
  'Tiruchi',
  'Tirunelveli',
  'Tenkasi Tamil Nadu',
  'Tiruppur',
  'Tirupur Tamil Nadu',
  'Tiruvannamalai',
  'Arunai Tamil Nadu',
  'Tonk',
  'Rajasthan',
  'Tuensang',
  'Nagaland',
  'Tumakuru',
  'Karnataka',
  'Udaipur',
  'Rajasthan',
  'Udalguri',
  'Assam',
  'Udham Singh Nagar',
  'Rudrapur Uttarakhand',
  'Udhampur',
  'Udupi',
  'Karnataka',
  'Ujjain',
  'Nagda',
  'Badnagar',

  'Ukhrul',
  'Manipur',
  'Umaria',

  'Una',
  'Himachal Pradesh',
  'Unnao',
  'Uttar Pradesh',
  'Unokoti',
  'Tripura',
  'Upper Dibang Valley',
  'AniniArunachal Pradesh',
  'Upper Siang',
  'YingkiongArunachal Pradesh',
  'Upper Subansiri',
  'DaporijoArunachal Pradesh',
  'Uttar Bastar Kanker',
  'Antagarh',
  'Bhanupratappur',
  'Charama',
  'Kanker',
  'Narharpur',
  'Pakhanjur',
  'Chhattisgarh',
  'Uttar Dinajpur',
  'West Bengal',
  'Uttara Kannada',
  'Karnataka',
  'Uttarkashi',
  'Purola',
  'Yamunotri',
  'Gangotri',
  'Uttarakhand',
  'Vadodara',
  'Dabhoi',
  'Karjan',
  'Padra',
  'Savli',
  'Sinor',
  'Waghodia',
  'Gujarat',
  'Vaishali',
  'Bihar',
  'Valsad',
  'Pardi',
  'Vapi',
  'Dharampur',
  'Kaparada',
  'Umbergaon',
  'Gujarat',
  'Varanasi',
  'Banaras',
  'Benaras',
  'Kashi',
  'Uttar Pradesh',
  'Vellore',
  'Vellur',
  'Vidisha',
  'Vijayapura',
  'Karnataka',
  'Vikarabad',
  'Telangana',
  'Viluppuram',
  'Kallakurichi ',
  'Virudhunagar',
  'VirudupattiTamil Nadu',
  'Visakhapatnam',
  'VizagapatamAndhra Pradesh',
  'Vizianagaram',
  'VijayanagaramAndhra Pradesh',
  'Wanaparthy',
  'Telangana',
  'Warangal Rural',
  'GeesugondaTelangana',
  'Warangal Urban',
  'Warangal city',
  'warangal',
  'Telangana',
  'Wardha',
  'Maharashtra',
  'Washim',
  'Maharashtra',
  'Wayanad',
  'Kerala',
  'West Champaran',
  'Bihar',
  'West Delhi',
  'Punjabi Bagh',
  'Paschim Vihar',
  'Janakpuri',
  'Kirti Nagar',
  'Delhi',
  'West District',
  'Sikkim West District',
  'Sikkim West',
  'Sikkim',
  'West Garo Hills',
  'Meghalaya',
  'West Godavari',
  'Paschima Godavari Jilla',
  'Eluru',
  'Andhra Pradesh',
  'West Jaintia Hills',
  'Meghalaya',
  'West Kameng',
  'BomdilaArunachal Pradesh',
  'West Karbi Anglong',
  'Assam',
  'West Khasi Hills',
  'Meghalaya',
  'West Siang',
  'Aalo',
  'Along',
  'Arunachal Pradesh',
  'West Tripura',
  'Tripura',
  'Wokha',
  'Nagaland',
  'Y.S.R.',
  'Kadapa',
  'Cuddapah',
  'Andhra Pradesh',
  'Yadadri Bhuvanagiri',
  'BhongiriTelangana',
  'Yadgir',
  'Karnataka',
  'Yamunanagar',
  'Jagadhri',
  'Chhachhrauli',
  'Sadhaura',
  'Adi Badri',
  'Bilaspur',
  'Radaur',
  'Haryana',
  'Yanam',
  'Puducherry',
  'Yavatmal',
  'Maharashtra',
  'Zunheboto',
  'Nagaland',
];
export const hints = {
  'hi-IN': commonHints,
  'en-IN': commonHints,
};
