/**
 * This code integrates voice queires to the dashboard with Slang.
 */

import Slang from 'slang-web-sdk';
import {buddyId, apiKey} from './buddy.js';
import './slang.css';
import ReactGA from 'react-ga';

let theDistricts = [];
let selectedLocale = localStorage.getItem('slangLocale') || 'en-IN';
const env = 'stage';
let speakOut = false;
let speakText = '';

ReactGA.initialize('UA-123830474-3');
// set the default selectable locales on the slang trigger
Slang.requestLocales(['en-IN', 'hi-IN']);
// Initialise Slang with the below params
Slang.initialize({
  buddyId,
  apiKey,
  env, // one of ['stage','prod']
  locale: selectedLocale, // one of ['en-IN','hi-IN']
  onSuccess: () => {
    console.log('Slang initialized successfully'); // anything you want to do once slang gets init successfully
    Slang.builtinUi.setConfig({
      overridenOnTriggerClick: async () => {
        const lastUsed = localStorage.getItem('SlangLastUsed' + selectedLocale);
        if (!lastUsed || Number(lastUsed) + 86400000 < Date.now()) {
          speakOut = true;
        } else {
          speakOut = false;
        }
        if (selectedLocale === 'hi-IN') {
          speakText =
            "आपका स्वागत है. अब अपने ज़िले में CoVid19 के पुष्ट मामलों की संख्या खोजने के लिए ज़िले का नाम बोले, जैसे की 'मुंबई'";
        } else {
          speakText =
            "Welcome. Now search for confirmed CoVid19 cases in your district by saying the district name, like 'Mumbai'";
        }
        Slang.startConversation(speakText, speakOut);
        localStorage.setItem('SlangLastUsed' + selectedLocale, Date.now());
      },
    });
  },
  onFailure: () => {
    console.log('Slang Failed to initialize'); // anything you want to do once slang fails to init
  },
});

// arrays of ASR biasing words for each locale
const hints = {
  'hi-IN': [
    'active',
    'recovered',
    'deceased',
    'cases',
    'confirmed',
    'active cases',
    'recovered cases',
    'deceased cases',
    'confirmed cases',
    'death',
    'died',
    'India',
    'Adilabad',
    'Telangana',
    'Agar Malwa',
    'Madhya Pradesh',
    'Agra',
    'Uttar Pradesh',
    'Ahmadabad',
    'AmdavadGujarat',
    'Ahmadnagar',
    'Ahmednagar',
    'Ahmednagar',
    'Maharashtra',
    'Aizawl',
    'Mizoram',
    'Ajmer',
    'Rajasthan',
    'Akola',
    'Maharashtra',
    'Alappuzha',
    'Kerala',
    'Aligarh',
    'Uttar Pradesh',
    'Alipurduar',
    'alipurdwarWest Bengal',
    'Alirajpur',
    'Madhya Pradesh',
    'Almora',
    'Dwarahat',
    'Ranikhet',
    'Someshwar',
    'Jageshwar',
    'Uttarakhand',
    'Alwar',
    'Rajasthan',
    'Ambala',
    'Mulana',
    'Naraingarh',
    'Haryana',
    'Ambedkar Nagar',
    'AkbarpurUttar Pradesh',
    'Amethi',
    'Uttar Pradesh',
    'Amravati',
    'Maharashtra',
    'Amreli',
    'Anumanji',
    'Amlik',
    'Amravat',
    'Gujarat',
    'Amritsar',
    'Punjab',
    'Amroha',
    'Jyotiba Phule Nagar',
    'Azizpura',
    'Uttar Pradesh',
    'Anand',
    'Khambhat',
    'Karamsad',
    'Tarapur',
    'Petlad',
    'Sojitra',
    'Gujarat',
    'Anantapur',
    'Anantapuramu',
    'Hindupur',
    'Andhra Pradesh',
    'Anantnag',
    'Jammu and Kashmir',
    'Anjaw',
    'HawaiArunachal Pradesh',
    'Anugul',
    'Odisha',
    'Anuppur',
    'Madhya Pradesh',
    'Araria',
    'Bihar',
    'Aravalli',
    'Aravalli',
    'Modasa',
    'Gujarat',
    'Ariyalur',
    'Tamil Nadu',
    'Arwal',
    'Bihar',
    'Ashoknagar',
    'Madhya Pradesh',
    'Auraiya',
    'Kannauj',
    'Etawah',
    'Uttar Pradesh',
    'Aurangabad',
    'Bihar',
    'Aurangabad',
    'Maharashtra',
    'Azamgarh',
    'AzamgadhUttar Pradesh',
    'Badgam',
    'Jammu and Kashmir',
    'Bagalkote',
    'Karnataka',
    'Bageshwar',
    'Uttarakhand',
    'Baghpat',
    'Uttar Pradesh',
    'Bahraich',
    'Uttar Pradesh',
    'Baksa',
    'Assam',
    'Balaghat',
    'Madhya Pradesh',
    'Balangir',
    'Odisha',
    'Baleshwar',
    'Odisha',
    'Ballari',
    'Karnataka',
    'Ballia',
    'Uttar Pradesh',
    'Balod',
    'Dalli RajharaChhattisgarh',
    'Baloda Bazar',
    'BhataparaChhattisgarh',
    'Balrampur',
    'Kusmi',
    'Rajpur',
    'Ramanujganj',
    'Ramchandarpur',
    'Shankargarh',
    'Wadrafnagar',
    'Chhattisgarh',
    'Balrampur',
    'Uttar Pradesh',
    'Bametara',
    'Bametara',
    'Nawagarh',
    'Saja',
    'Chhattisgarh',
    'Banas Kantha',
    'banaskanthaGujarat',
    'Banda',
    'Uttar Pradesh',
    'Bandipore',
    'Jammu and Kashmir',
    'Banka',
    'Bihar',
    'Bankura',
    'West Bengal',
    'Banswara',
    'Rajasthan',
    'Bara Banki',
    'BarabankiUttar Pradesh',
    'Baramula',
    'Jammu and Kashmir',
    'Baran',
    'Rajasthan',
    'Bareilly',
    'Uttar Pradesh',
    'Bargarh',
    'Odisha',
    'Barmer',
    'Rajasthan',
    'Barnala',
    'Punjab',
    'Barpeta',
    'Assam',
    'Barwani',
    'Madhya Pradesh',
    'Bastar',
    'Darba',
    'Frezarpur',
    'Hatkachora',
    'Jagdalpur',
    'Jagdalpur',
    'Sosanpal',
    'Chhattisgarh',
    'Basti',
    'Uttar Pradesh',
    'Bathinda',
    'Punjab',
    'Baudh',
    'Odisha',
    'Begusarai',
    'Bihar',
    'Belagavi',
    'Karnataka',
    'Bengaluru',
    'Karnataka',
    'Bengaluru Rural',
    'Karnataka',
    'Betul',
    'Madhya Pradesh',
    'Bhadohi',
    'Uttar Pradesh',
    'Bhadradri Kothagudem',
    'KothagudemTelangana',
    'Bhadrak',
    'Odisha',
    'Bhagalpur',
    'Bihar',
    'Bhandara',
    'Maharashtra',
    'Bharatpur',
    'Rajasthan',
    'Bharuch',
    'broach',
    'Amirgadh',
    'Bhabhar',
    'Dantiwada',
    'Danta',
    'Deesa',
    'Deodar',
    'Dhanera',
    'Palanpur',
    'Sihori (Kankrej)',
    'Tharad',
    'Vadgam',
    'Lakhni',
    'Suigam',
    'Vav',
    'Gujarat',
    'Bhavnagar',
    'Bhavnagar',
    'Sihor',
    'Umrala',
    'Gariadhar',
    'Palitana',
    'Mahuva',
    'Talaja',
    'Ghogha',
    'Jesar',
    'Vallbhipur.',
    'Gujarat',
    'Bhilwara',
    'Rajasthan',
    'Bhind',
    'Madhya Pradesh',
    'Bhiwani',
    'Bhiwani',
    'Loharu',
    'Siwani',
    'Tosham',
    'Haryana',
    'Bhojpur',
    'ArrahBihar',
    'Bhopal',
    'Madhya Pradesh',
    'Bid',
    'Beed',
    'Beed',
    'Maharashtra',
    'Bidar',
    'Karnataka',
    'Bijapur',
    'Bijapur',
    'Bhopalpatnam',
    'Chhattisgarh',
    'Bijnor',
    'Uttar Pradesh',
    'Bikaner',
    'Rajasthan',
    'Bilaspur',
    'Baitalpur',
    'Bilha',
    'Bodri',
    'Deori',
    'Gaurella',
    'Ghutku',
    'Kota',
    'Lingiyadih',
    'Mehmand',
    'Pendra',
    'Ratanpur',
    'Sirgiti',
    'Takhatpur',
    'Chhattisgarh',
    'Bilaspur',
    'Himachal Pradesh',
    'Birbhum',
    'West Bengal',
    'Bishnupur',
    'Manipur',
    'Biswanath',
    'Biswanath Chariali',
    '',
    'Assam',
    'Bokaro',
    'Jharkhand',
    'Bongaigaon',
    'Assam',
    'Botad',
    'Bitad',
    'Gadhada',
    'Barvala',
    'Ranpur',
    'Gujarat',
    'Budaun',
    'Uttar Pradesh',
    'Bulandshahr',
    'Bulandshahar',
    'Khurja',
    'Uttar Pradesh',
    'Buldana',
    'BuldhanaMaharashtra',
    'Bundi',
    'Rajasthan',
    'Burhanpur',
    'Madhya Pradesh',
    'Buxar',
    'BalliaBihar',
    'Cachar',
    'Assam',
    'Central Delhi',
    'Cannaught Place',
    'CP',
    '',
    'Delhi',
    'Chamarajanagara',
    'Karnataka',
    'Chamba',
    'Himachal Pradesh',
    'Chamoli',
    'Badrinath',
    'Karnprayag',
    'Tharali',
    'Uttarakhand',
    'Champawat',
    'Uttarakhand',
    'Champhai',
    'Mizoram',
    'Chandauli',
    'Uttar Pradesh',
    'Chandel',
    'Manipur',
    'Chandigarh',
    'Chandigarh',
    'Chandrapur',
    'Maharashtra',
    'Changlang',
    'Arunachal Pradesh',
    'Charaideo',
    'Assam',
    'Charki Dadri',
    'BadhraHaryana',
    'Chatra',
    'Jharkhand',
    'Chennai',
    'Tamil Nadu',
    'Chhatarpur',
    'Madhya Pradesh',
    'Chhindwara',
    'Madhya Pradesh',
    'Chikkaballapura',
    'Karnataka',
    'Chikkamagaluru',
    'Karnataka',
    'Chirang',
    'Assam',
    'Chitradurga',
    'Karnataka',
    'Chitrakoot',
    'Uttar Pradesh',
    'Chittaurgarh',
    'Rajasthan',
    'Chittoor',
    'Andhra Pradesh',
    'Chota Udaipur',
    'Chhota Udepur',
    'Pavi Jetpur',
    'Kawant',
    'Naswadi',
    'Sankheda',
    'Bodeli',
    'Gujarat',
    'Churachandpur',
    'Manipur',
    'Churu',
    'Rajasthan',
    'Coimbatore',
    'Tamil Nadu',
    'Cooch Behar',
    'Coochbehar',
    'Koch Bihar',
    'West Bengal',
    'Cuddalore',
    'Tamil Nadu',
    'Cuttack',
    'Odisha',
    'Dadra and Nagar Haveli',
    'Dadra and Nagar Haveli',
    'Dakshin Bastar Dantewada',
    'Bade Bacheli',
    'Dantewada',
    'Geedam',
    'Katekalyan',
    'Kirandul',
    'Kuwakonda',
    'Penta',
    'Chhattisgarh',
    'Dakshin Dinajpur',
    'South DinajpurWest Bengal',
    'Dakshina Kannada',
    'Karnataka',
    'Daman',
    'Daman And Diu',
    'Damoh',
    'Madhya Pradesh',
    'Darbhanga',
    'Bihar',
    'Darjeeling',
    'West Bengal',
    'Darrang',
    'Assam',
    'Datia',
    'Madhya Pradesh',
    'Dausa',
    'Rajasthan',
    'Davanagere',
    'Karnataka',
    'Debagarh',
    'Odisha',
    'Dehradun',
    'Mussoorie',
    'Rishikesh',
    'Uttarakhand',
    'Deoghar',
    'Jharkhand',
    'Deoria',
    'Uttar Pradesh',
    'Devbhumi Dwarka',
    'Dwarka',
    'Bhanvad',
    'Kalyanpur',
    'Khambaila',
    'Gujarat',
    'Dewas',
    'Madhya Pradesh',
    'Dhalai',
    'Tripura',
    'Dhamtari',
    'Bagoud',
    ' Kurud',
    'Nagri',
    'Dhamtari',
    'Chhattisgarh',
    'Dhanbad',
    'Jharkhand',
    'Dhar',
    'PithampurMadhya Pradesh',
    'Dharmapuri',
    'dharmapuriTamil Nadu',
    'Dharwad',
    'Karnataka',
    'Dhaulpur',
    'Rajasthan',
    'Dhemaji',
    'Assam',
    'Dhenkanal',
    'Odisha',
    'Dhubri',
    'Assam',
    'Dhule',
    'Maharashtra',
    'Dibrugarh',
    'Assam',
    'Dima Hasao',
    'Assam',
    'Dimapur',
    'Nagaland',
    'Dindigul',
    'Tamil Nadu',
    'Dindori',
    'Madhya Pradesh',
    '',
    '',
    'Diu',
    'Daman And Diu',
    'Doda',
    'Jammu and Kashmir',
    'Dohad',
    'Dahod',
    'Jhalod',
    'Devgarh',
    'Garbada',
    'Limkheda',
    'Fatehpur',
    'Dhanpur',
    'Sanjeli',
    'Gujarat',
    'Dumka',
    'Jharkhand',
    'Dungarpur',
    'Rajasthan',
    'Durg',
    'Bhilai',
    ' Durg',
    ' Ahiwara',
    'Bhilai Charoda',
    'Dhamdha',
    'Jamul',
    'Khamhria',
    'Kumhari',
    'Mahamaya',
    'Parpodi',
    'Patan',
    'Chhattisgarh',
    'East Champaran',
    'Bihar',
    'East Delhi',
    'Dilshad Garden',
    'Mayur vihar',
    'Parpatganj',
    'Delhi',
    'East District',
    'Sikkim East District',
    'Sikkim East',
    'Sikkim',
    'East Garo Hills',
    'Meghalaya',
    'East Godavari',
    'KakinadaAndhra Pradesh',
    'East Jaintia Hills',
    'Meghalaya',
    'East Kameng',
    'SeppaArunachal Pradesh',
    'East Khasi Hills',
    'Meghalaya',
    'East Siang',
    'PasighatArunachal Pradesh',
    'Ernakulam',
    'Kerala',
    'Erode',
    'Tamil Nadu',
    'Etah',
    'Uttar Pradesh',
    'Etawah',
    'Uttar Pradesh',
    'Faizabad',
    'AyodhyaUttar Pradesh',
    'Faridabad',
    'Nuh',
    'Palwal',
    'Haryana',
    'Faridkot',
    'Punjab',
    'Farrukhabad',
    'FategarhUttar Pradesh',
    'Fatehabad',
    'Ratia',
    'Tohana',
    'Haryana',
    'Fatehgarh Sahib',
    'Punjab',
    'Fatehpur',
    'Uttar Pradesh',
    'Fazilka',
    'AboharPunjab',
    'Firozabad',
    'ShikohabadUttar Pradesh',
    'Firozpur',
    'Punjab',
    'Gadag',
    'Karnataka',
    'Gadchiroli',
    'Maharashtra',
    'Gajapati',
    'Odisha',
    'Ganderbal',
    'Jammu and Kashmir',
    'Gandhinagar',
    'Motera',
    'Adala',
    'Kalol INA',
    'Dahegam',
    'Mansa',
    'Gujarat',
    'Ganganagar',
    'Rajasthan',
    'Ganjam',
    'BerhampurOdisha',
    'Garhwa',
    'Jharkhand',
    'Gariaband',
    'GariabandChhattisgarh',
    'Gautam Buddha Nagar',
    'Noida',
    'Greater Noida',
    'Uttar Pradesh',
    'Gaya',
    'Bihar',
    'Ghaziabad',
    'ModinagarUttar Pradesh',
    'Ghazipur',
    'Uttar Pradesh',
    'Gir Somnath',
    'Veraval',
    'Talala',
    'Sutrapada',
    'Kodinar',
    'Una',
    'Gir-Gadhada',
    'Gujarat',
    'Giridih',
    'Jharkhand',
    'Goalpara',
    'Assam',
    'Godda',
    'Jharkhand',
    'Golaghat',
    'Assam',
    'Gomati',
    'Tripura',
    'Gonda',
    'Uttar Pradesh',
    'Gondiya',
    'GondiaMaharashtra',
    'Gopalganj',
    'Bihar',
    'Gorakhpur',
    'Uttar Pradesh',
    'Gumla',
    'Jharkhand',
    'Guna',
    'Madhya Pradesh',
    'Guntur',
    'Andhra Pradesh',
    'Gurdaspur',
    'BatalaPunjab',
    'Gurugram',
    'Sohna',
    'Pataudi',
    'Farukh Nagar',
    'Manesar',
    'gurgaon',
    'Haryana',
    'Gwalior',
    'Madhya Pradesh',
    'Hailakandi',
    'Assam',
    'Hamirpur',
    'Himachal Pradesh',
    'Hamirpur',
    'Uttar Pradesh',
    'Hanumangarh',
    'Rajasthan',
    'Hapur',
    'Uttar Pradesh',
    'Harda',
    'Madhya Pradesh',
    'Hardoi',
    'Uttar Pradesh',
    'Haridwar',
    'RoorkeeUttarakhand',
    'Hassan',
    'Karnataka',
    'Hathras',
    'Uttar Pradesh',
    'Haveri',
    'Karnataka',
    'Hazaribagh',
    'Jharkhand',
    'Hingoli',
    'Maharashtra',
    'Hisar',
    'Adampur',
    'Agroha',
    'Barwala',
    'Hansi',
    'Narnaund',
    'Uklanamandi',
    'Haryana',
    'Hojai',
    'Assam',
    'Hooghly',
    'Hoogli',
    'Hugli',
    'West Bengal',
    'Hoshangabad',
    'ItarsiMadhya Pradesh',
    'Hoshiarpur',
    'Punjab',
    'Howrah',
    'West Bengal',
    'Hyderabad',
    'Telangana',
    'Idukki',
    'Kerala',
    'Imphal East',
    'Manipur',
    'Imphal West',
    'Manipur',
    'Indore',
    'Madhya Pradesh',
    'Jabalpur',
    'Madhya Pradesh',
    'Jagatsinghapur',
    'Odisha',
    'Jagitial',
    'Telangana',
    'Jaipur',
    'Rajasthan',
    'Jaisalmer',
    'Rajasthan',
    'Jajapur',
    'Odisha',
    'Jalandhar',
    'Punjab',
    'Jalaun',
    'OraiUttar Pradesh',
    'Jalgaon',
    'BhusawalMaharashtra',
    'Jalna',
    'Maharashtra',
    'Jalore',
    'Rajasthan',
    'Jalpaiguri',
    'West Bengal',
    'Jammu',
    'Jammu and Kashmir',
    'Jamnagar',
    'Jam Jodhpur',
    'Jodiya',
    'DhrolJamnagar',
    'Lalpur',
    'Kalavad',
    'Gujarat',
    'Jamtara',
    'Jharkhand',
    'Jamui',
    'Bihar',
    'Jangoan',
    'Telangana',
    'Janjgir Champa',
    'Adbhar',
    'Akaltara',
    'Baloda',
    'Champa',
    'Janjgir',
    'Kharod',
    'Naila-Janjgir',
    'Naya Baradwar',
    'Pamgarh',
    'Sakti',
    'Shivrinarayan',
    'Chhattisgarh',
    'Jashpur',
    'Jashpur Nagar',
    'Kunkuri',
    'Pathalgaon',
    'Chhattisgarh',
    'Jaunpur',
    'Uttar Pradesh',
    'Jayashankar',
    'Bhupalpalle',
    'Jayashankar Bhupalpally',
    'Telangana',
    'Jehanabad',
    'Bihar',
    'Jhabua',
    'Madhya Pradesh',
    'Jhajjar',
    'Bahadurgarh',
    'Badli',
    'Beri',
    'Haryana',
    'Jhalawar',
    'Rajasthan',
    'Jhansi',
    'Uttar Pradesh',
    'Jhargram',
    'West Bengal',
    'Jharsuguda',
    'Odisha',
    'Jhunjhunu',
    'Rajasthan',
    'Jind',
    'Narwana',
    'Safidon',
    'Haryana',
    'Jiribam',
    'Manipur',
    'Jodhpur',
    'Rajasthan',
    'Jogulamba Gadwal',
    'GadwalTelangana',
    'Jorhat',
    'Assam',
    'Junagadh',
    'Junagadh',
    'Bhesan',
    'Junagadhl',
    'Keshod',
    'Malia',
    'Manavadar',
    'Mangrol',
    'Mendarda',
    'Vanthali',
    'Visavadar',
    'Gujarat',
    'Kabeerdham',
    'Kabirdham',
    'Chilpi',
    'Kawardha',
    'Pandariya',
    'Pandatarai',
    'Chhattisgarh',
    'Kachchh',
    'Abdasa',
    'Anjar',
    'Bhachau',
    'Bhuj',
    'Gandhidham',
    'Lakhpat',
    'Mandvi',
    'Mundra',
    'Nakhatrana',
    'Rapar',
    'Gujarat',
    'Kaimur Bhabua',
    'Bihar',
    'Kaithal',
    'Guhla',
    'Pundri',
    'Kalayat',
    'Haryana',
    'Kakching',
    'Manipur',
    'Kalaburagi',
    'GulbargaKarnataka',
    'Kalahandi',
    'bhawanipatnaOdisha',
    'Kalimpong',
    'West Bengal',
    'Kamareddy',
    'Telangana',
    'Kamjong',
    'Manipur',
    'Kamle',
    'Khamle',
    'Raga',
    'Arunachal Pradesh',
    'Kamrup',
    'Assam',
    'Kamrup Metropolitan',
    'GuwahatiAssam',
    'Kancheepuram',
    'KanchipuramTamil Nadu',
    'Kandhamal',
    'Odisha',
    'Kangpokpi',
    'Manipur',
    'Kangra',
    'Himachal Pradesh',
    'Kanker',
    'Bhanupratappur',
    'Kapsi',
    'Pakhanjore',
    '',
    'Kannauj',
    'Uttar Pradesh',
    'Kanniyakumari',
    'KanyakumariTamil Nadu',
    'Kannur',
    'Kerala',
    'Kanpur Dehat',
    'Uttar Pradesh',
    'Kanpur Nagar',
    'Kanpur city',
    'Kanpur',
    'Uttar Pradesh',
    'Kapurthala',
    'PhagwaraPunjab',
    'Karaikal',
    'Puducherry',
    'Karauli',
    'Rajasthan',
    'Karbi Anglong',
    'Assam',
    'Kargil',
    'Ladakh',
    'Karimganj',
    'Assam',
    'Karimnagar',
    'Telangana',
    'Karnal',
    'Nilokheri',
    'Indri',
    'Gharaunda',
    'Assandh',
    'Haryana',
    'Karur',
    'Tamil Nadu',
    'Kasaragod',
    'Kerala',
    'Kasganj',
    'Uttar Pradesh',
    'Kathua',
    'Jammu and Kashmir',
    'Katihar',
    'Bihar',
    'Katni',
    'MurwaraMadhya Pradesh',
    'Kaushambi',
    'Uttar Pradesh',
    'Kendrapara',
    'Odisha',
    'Kendujhar',
    'Odisha',
    'Khagaria',
    'Bihar',
    'Khammam',
    'Telangana',
    'Khandwa',
    'East NimarMadhya Pradesh',
    'Khargone',
    'West NimarMadhya Pradesh',
    'Kheda',
    'Nadiad',
    'Thasra',
    'Kapadvanj',
    'Mehmedabad',
    'Kathlal',
    'Matar',
    'Mahudha',
    'Kaira',
    'Gujarat',
    'Kheri',
    'Lakhimpur KheriUttar Pradesh',
    'Khordha',
    'BhubhaneshwarOdisha',
    'Khowai',
    'Tripura',
    'Khunti',
    'Jharkhand',
    'Kinnaur',
    'Himachal Pradesh',
    'Kiphire',
    'Nagaland',
    'Kishanganj',
    'Bihar',
    'Kishtwar',
    'Jammu and Kashmir',
    'Kodagu',
    'coorgKarnataka',
    'Kodarma',
    'Jharkhand',
    'Kohima',
    'Nagaland',
    'Kokrajhar',
    'Assam',
    'Kolar',
    'Karnataka',
    'Kolasib',
    'Mizoram',
    'Kolhapur',
    'Maharashtra',
    'Kolkata',
    'CalcuttaWest Bengal',
    'Kollam',
    'Kerala',
    'Kondagaon',
    'Keskal',
    'Pharasgaon',
    'Chhattisgarh',
    'Koppal',
    'Karnataka',
    'Koraput',
    'Odisha',
    'Korba',
    'Banki Mongra',
    'Dipka',
    'Katghora',
    'Korba',
    'Rajgamar',
    'Chhattisgarh',
    'Koriya',
    'Baikunthpur',
    'Koriya',
    'Chharchha',
    'Chirmiri',
    'Jhagrakhand',
    'Khongapani',
    'Manendragarh',
    'Chhattisgarh',
    'Kota',
    'Rajasthan',
    'Kottayam',
    'Kerala',
    'Kozhikode',
    'Kerala',
    'Kra Daadi',
    'New Palin',
    'Jamin',
    'Arunachal Pradesh',
    'Krishna',
    'Vijayawada',
    'Machilipatnam',
    'Andhra Pradesh',
    'Krishnagiri',
    'Tamil Nadu',
    'Kulgam',
    'Jammu and Kashmir',
    'Kullu',
    'Himachal Pradesh',
    'Kumuram Bheem Asifabad',
    'AsifabadTelangana',
    'Kupwara',
    'Jammu and Kashmir',
    'Kurnool',
    'Andhra Pradesh',
    'Kurukshetra',
    'Thanesar',
    'Pehowa',
    'Haryana',
    'Kurung Kumey',
    'KoloriangArunachal Pradesh',
    'Kushinagar',
    'Uttar Pradesh',
    'Lahul and Spiti',
    'Himachal Pradesh',
    'Lakhimpur',
    'Assam',
    'Lakhisarai',
    'Bihar',
    'Lakshadweep',
    'Lakshadweep',
    'Lalitpur',
    'Uttar Pradesh',
    'Latehar',
    'Jharkhand',
    'Latur',
    'Maharashtra',
    'Lawngtlai',
    'Mizoram',
    'Leh',
    'Ladakh',
    'Lepa Rada',
    'BasarArunachal Pradesh',
    'Lohardaga',
    'Jharkhand',
    'Lohit',
    'TezuArunachal Pradesh',
    'Longding',
    'Arunachal Pradesh',
    'Longleng',
    'Nagaland',
    'Lower Dibang Valley',
    'RoingArunachal Pradesh',
    'Lower Siang',
    'LikabaliArunachal Pradesh',
    'Lower Subansiri',
    'ZiroArunachal Pradesh',
    'Lucknow',
    'Uttar Pradesh',
    'Ludhiana',
    'Punjab',
    'Lunglei',
    'Mizoram',
    'Madhepura',
    'Bihar',
    'Madhubani',
    'Bihar',
    'Madurai',
    'Tamil Nadu',
    'Mahabubabad',
    'Telangana',
    'Mahabubnagar',
    'Telangana',
    'Mahasamund',
    'Bagbahara',
    'Basna',
    'Mahasamund',
    'Pithora',
    'Saraipali',
    'Sirpur',
    'Chhattisgarh',
    'Mahe',
    'Puducherry',
    'Mahendragarh',
    'Narnaul',
    'Nangal Chowdhary',
    'Kanina Mahendragarh',
    'Ateli',
    'Haryana',
    'Mahesana',
    'Vijapur',
    'Bahucharaji',
    'Satlasana',
    'Modhera',
    'Unjha',
    'Vadnagar',
    'Kalol',
    'Kadi',
    'Visnagar',
    'Kherva',
    'Jotana',
    'Kheralu',
    'Gujarat',
    'Mahisagar',
    'Balasinor',
    'Lunavada',
    'Kadana',
    'Virpur',
    'Santrampur',
    'Khanpur',
    'Gujarat',
    'Mahoba',
    'Uttar Pradesh',
    'Mahrajganj',
    'Uttar Pradesh',
    'Mainpuri',
    'Uttar Pradesh',
    'Majuli',
    'Assam',
    'Malappuram',
    'Kerala',
    'Maldah',
    'Malda',
    'Maldaha',
    'West Bengal',
    'Malkangiri',
    'Odisha',
    'Mamit',
    'Mizoram',
    'Mancherial',
    'Telangana',
    'Mandi',
    'Himachal Pradesh',
    'Mandla',
    'Madhya Pradesh',
    'Mandsaur',
    'Madhya Pradesh',
    'Mandya',
    'Karnataka',
    'Mansa',
    'Punjab',
    'Mathura',
    'Vrindavan',
    'Mathura Vrindavan',
    'Uttar Pradesh',
    'Mau',
    'Uttar Pradesh',
    'Mayurbhanj',
    'baripadaOdisha',
    'Medak',
    'Telangana',
    'Medchal Malkajgiri',
    'Telangana',
    'Medinipur East',
    'Purba Medinipur',
    'East Medinipur',
    'East Midnapore',
    'Midnapore East',
    'West Bengal',
    'Medinipur West',
    'Paschim Medinipur',
    'West Midnapore',
    'Midnapore West',
    'West Bengal',
    'Meerut',
    'Uttar Pradesh',
    'Mirpur',
    'Jammu and Kashmir',
    'Mirzapur',
    'Uttar Pradesh',
    'Moga',
    'Punjab',
    'Mokokchung',
    'Nagaland',
    'Mon',
    'Nagaland',
    'Moradabad',
    'Uttar Pradesh',
    'Morbi',
    'Maliya',
    'Tankara',
    'Wankaner',
    'Rajkot',
    'Halvad ',
    'Gujarat',
    'Morena',
    'Madhya Pradesh',
    'Morigaon',
    'Assam',
    'Mulugu',
    'Telangana',
    'Mumbai',
    'BombayMaharashtra',
    'Mumbai Suburban',
    'Maharashtra',
    'Mungeli',
    'Lormi',
    'Mungeli',
    'Chhattisgarh',
    'Munger',
    'Bihar',
    'Murshidabad',
    'West Bengal',
    'Muzaffarabad',
    'Jammu and Kashmir',
    'Muzaffarnagar',
    'Uttar Pradesh',
    'Muzaffarpur',
    'Bihar',
    'Mysuru',
    'Karnataka',
    'Nabarangapur',
    'Odisha',
    'Nadia',
    'West Bengal',
    'Nagaon',
    'Assam',
    'Nagapattinam',
    'Mayiladuthurai',
    'Nagapatnam',
    'Tamil Nadu',
    'Nagarkurnool',
    'Telangana',
    'Nagaur',
    'Rajasthan',
    'Nagpur',
    'Maharashtra',
    'Nainital',
    'Haldwani',
    'Lalkua',
    'Bhimtal',
    'Kaladhungi',
    'Ramnagar',
    'Uttarakhand',
    'Nalanda',
    'Bihar',
    'Nalbari',
    'Assam',
    'Nalgonda',
    'Telangana',
    'Namakkal',
    'Tamil Nadu',
    'Namsai',
    'Arunachal Pradesh',
    'Nanded',
    'Maharashtra',
    'Nandurbar',
    'Maharashtra',
    'Narayanpet',
    'Telangana',
    'Narayanpur',
    'NarayanpurChhattisgarh',
    'Narmada',
    'Tilakwada',
    'Garudeshwar',
    'Nandod',
    'Dediyapada',
    'Sagbara.',
    'Gujarat',
    'Narsimhapur',
    'Madhya Pradesh',
    'Nashik',
    'Maharashtra',
    'Navsari',
    'Jalalpore',
    'Gandevi',
    'Chikhli',
    'Khergam',
    'Bansda',
    'Gujarat',
    'Nawada',
    'Bihar',
    'Nayagarh',
    'Odisha',
    'Neemuch',
    'Madhya Pradesh',
    'New Delhi',
    'Delhi',
    'Dilli',
    'Purani Dilli',
    'Old delhi',
    'Delhi',
    'Nicobars',
    'Carnicobar',
    'Campbell Bay',
    'Indira point',
    'Andaman and Nicobar Islands',
    'Nirmal',
    'Telangana',
    'Niwari',
    'Madhya Pradesh',
    'Nizamabad',
    'Telangana',
    'Noney',
    'Manipur',
    'North 24 Parganas',
    '24 paraganas northWest Bengal',
    'North and Middle Andaman',
    'DiglipurAndaman and Nicobar Islands',
    'North Delhi',
    'Rohini',
    'Narela',
    'Delhi',
    'North District',
    'Sikkim North District',
    'Sikkim North',
    'Sikkim',
    'North East Delhi',
    'Tahirpur',
    'Maujpur',
    'Delhi',
    'North Garo Hills',
    'Meghalaya',
    'North Goa',
    'Goa',
    'North Tripura',
    'Tripura',
    'North West Delhi',
    'Pitampura',
    'Shalimar Bagh',
    'Delhi',
    'Nuapada',
    'Odisha',
    'Nuh',
    'Ferozepur Jhirka',
    'Punahana',
    'Taoru',
    'Haryana',
    'Osmanabad',
    'Maharashtra',
    'Pakke Kessang',
    'LemmiArunachal Pradesh',
    'Pakur',
    'Jharkhand',
    'Palakkad',
    'Kerala',
    'Palamu',
    'Jharkhand',
    'Palghar',
    'Carved out of Thane',
    'Vasai-Virar falls in Palgarh for example',
    'Maharashtra',
    'Pali',
    'Rajasthan',
    'Palwal',
    'Haryana',
    'Panch Mahals',
    'Godhra',
    'Halol',
    'Kalol',
    'Jambughoda',
    'Shahera',
    'Morva Hadaf',
    'Goghamba',
    'panchmahal',
    'Gujarat',
    'Panchkula',
    'KalkaHaryana',
    'Panipat',
    'SamalkhaHaryana',
    'Panna',
    'Madhya Pradesh',
    'Papum Pare',
    'YupiaArunachal Pradesh',
    'Parbhani',
    'Maharashtra',
    'Paschim Bardhaman',
    'West Bengal',
    'Pashchimi Singhbhum',
    'Jharkhand',
    'Patan',
    'Sidhpur',
    'Harij',
    'Radhanpur',
    'Sami',
    'Shankeshwar',
    'Santalpur',
    'Sarasvati',
    'Chanasma',
    'Gujarat',
    'Pathanamthitta',
    'Kerala',
    'Pathankot',
    'Punjab',
    'Patiala',
    'RajpuraPunjab',
    'Patna',
    'Bihar',
    'Pauri Garhwal',
    'Pauri',
    'Garhwal',
    'Kotdwara',
    'Dhumakot',
    'Uttarakhand',
    'Peddapalli',
    'Telangana',
    'Perambalur',
    'Perambalur',
    'Perumpuliur',
    'Perumpuliyur',
    'Tamil Nadu',
    'Peren',
    'Nagaland',
    'Phek',
    'Nagaland',
    'Pherzawl',
    'Manipur',
    'Pilibhit',
    'Uttar Pradesh',
    'Pithoragarh',
    'Dharchhula',
    'Didihat',
    'Gangolihat',
    'Uttarakhand',
    'Porbandar',
    'Ranavav',
    'Kutiyana',
    'Gujarat',
    'Prakasam',
    'OngoleAndhra Pradesh',
    'Pratapgarh',
    'Rajasthan',
    'Pratapgarh',
    'Uttar Pradesh',
    'Prayagraj',
    'Allahabad',
    'Illahabad',
    'Prayag',
    'Uttar Pradesh',
    'Puducherry',
    'PondicherryPuducherry',
    'Pudukkottai',
    'Thondaiman seemai',
    'The New Fort',
    'Tamil Nadu',
    'Pulwama',
    'Jammu and Kashmir',
    'Punch',
    'Jammu and Kashmir',
    'Pune',
    'Pune City',
    'Pune Rural',
    'Maharashtra',
    'Purba Bardhaman',
    'West Bengal',
    'Purbi Singhbhum',
    'JamshedpurJharkhand',
    'Puri',
    'Odisha',
    'Purnia',
    'Bihar',
    'Purulia',
    'puruliyaWest Bengal',
    'Rae Bareli',
    'RaebareliUttar Pradesh',
    'Raichur',
    'Karnataka',
    'Raigarh',
    'Dadar',
    'Dharamjaigarh',
    'Gharghoda',
    'Kharsia',
    'Raigarh',
    'Sarangarh',
    'Tamnar',
    'Tetla',
    'Chhattisgarh',
    'Raigarh',
    'Alibag',
    'Alibaug',
    'Maharashtra',
    'Raipur',
    'Naya Raipur',
    'Abhanpur',
    'Arang',
    'Baikunth',
    'Banarsi',
    'Bhanpuri',
    'Bhatgaon',
    'Birgaon',
    'Gobranawapara',
    'Gogaon',
    'Mowa',
    'Raipur',
    'Rajim',
    'Simga',
    'Tilda Newra',
    'Urla',
    'Chhattisgarh',
    'Raisen',
    'Madhya Pradesh',
    'Rajanna Sircilla',
    'SircillaTelangana',
    'Rajgarh',
    'Madhya Pradesh',
    'Rajkot',
    'Paddhari',
    'Lodhika',
    'Dhoraji',
    'Rajkot',
    'Jam Kandorna',
    'Upleta',
    'Jetpur',
    'Kotda Sangani',
    'Jasdan',
    'Vinchhiya',
    'Gondal',
    'Gujarat',
    'Rajnandgaon',
    'Ambagarh Chowki',
    'Chhuikhadan',
    'Dongargarh',
    'Dongergaon',
    'Gandai',
    'Khairagarh',
    'Rajnandgaon',
    'Chhattisgarh',
    'Rajouri',
    'Jammu and Kashmir',
    'Rajsamand',
    'Rajasthan',
    'Ramanagara',
    'Karnataka',
    'Ramanathapuram',
    'RamanadTamil Nadu',
    'Ramban',
    'Jammu and Kashmir',
    'Ramgarh',
    'Jharkhand',
    'Rampur',
    'Uttar Pradesh',
    'Ranchi',
    'Jharkhand',
    'Ranga Reddy',
    'ShamshabadTelangana',
    'Ratlam',
    'Madhya Pradesh',
    'Ratnagiri',
    'Maharashtra',
    'Rayagada',
    'Odisha',
    'Reasi',
    'Jammu and Kashmir',
    'Rewa',
    'Madhya Pradesh',
    'Rewari',
    'Kosli',
    'Bawal',
    'Haryana',
    'Ribhoi',
    'Meghalaya',
    'Rohtak',
    'Meham',
    'Rothasgarh',
    'Haryana',
    'Rohtas',
    'Bihar',
    'Rudraprayag',
    'Darmola',
    'Kedarnath',
    'Uttarakhand',
    'Rupnagar',
    'Punjab',
    'S.A.S. Nagar',
    'Sahibzada Ajit Singh Nagar',
    'Mohali',
    'Punjab',
    'S.P.S. Nellore',
    'Sri Potti Sriramulu Nellore',
    'Nellore',
    'Andhra Pradesh',
    'Sabar Kantha',
    'Himatnagar',
    'Idar',
    'Prantij',
    'Talod',
    'Khedbrahma',
    'Vadali',
    'Vijaynagar',
    'Poshina',
    'sabarkantha',
    'Gujarat',
    'Sagar',
    'Madhya Pradesh',
    'Saharanpur',
    'Uttar Pradesh',
    'Saharsa',
    'Bihar',
    'Sahibganj',
    'Jharkhand',
    'Saiha',
    'Mizoram',
    'Salem',
    'Tamil Nadu',
    'Samastipur',
    'Bihar',
    'Samba',
    'Jammu and Kashmir',
    'Sambalpur',
    'Odisha',
    'Sambhal',
    'Uttar Pradesh',
    'Sangareddy',
    'Telangana',
    'Sangli',
    'Maharashtra',
    'Sangrur',
    'Sunam',
    'Malerkotla',
    'Punjab',
    'Sant Kabir Nagar',
    'Uttar Pradesh',
    'Saraikela-Kharsawan',
    'Jharkhand',
    'Saran',
    'Bihar',
    'Satara',
    'MahabaleshwarMaharashtra',
    'Satna',
    'Madhya Pradesh',
    'Sawai Madhopur',
    'Rajasthan',
    'Sehore',
    'Madhya Pradesh',
    'Senapati',
    'Manipur',
    'Seoni',
    'Madhya Pradesh',
    'Serchhip',
    'Mizoram',
    'Shahdara',
    'Yamuna ViharDelhi',
    'Shahdol',
    'Madhya Pradesh',
    'Shahid Bhagat Singh Nagar',
    'Nawanshahr',
    'Punjab',
    'Shahjahanpur',
    'Uttar Pradesh',
    'Shajapur',
    'Madhya Pradesh',
    'Shamli',
    'Uttar Pradesh',
    'Sheikhpura',
    'Bihar',
    'Sheohar',
    'Bihar',
    'Sheopur',
    'Madhya Pradesh',
    'Shi Yomi',
    'TatoArunachal Pradesh',
    'Shimla',
    'Himachal Pradesh',
    'Shivamogga',
    'ShimogaKarnataka',
    'Shivpuri',
    'Madhya Pradesh',
    'Shrawasti',
    'Uttar Pradesh',
    'Shupiyan',
    'Jammu and Kashmir',
    'Siang',
    'Boleng',
    'Pangin',
    'Arunachal Pradesh',
    'Siddharthnagar',
    'Uttar Pradesh',
    'Siddipet',
    'Telangana',
    'Sidhi',
    'Madhya Pradesh',
    'Sikar',
    'Rajasthan',
    'Simdega',
    'Jharkhand',
    'Sindhudurg',
    'Maharashtra',
    'Singrauli',
    'Madhya Pradesh',
    'Sipahijala',
    'Tripura',
    'Sirmaur',
    'Himachal Pradesh',
    'Sirohi',
    'Rajasthan',
    'Sirsa',
    'Dabwali',
    'Rania',
    'Kalanwali',
    'Ellenabad',
    'Sirsapattan',
    'Haryana',
    'Sitamarhi',
    'Bihar',
    'Sitapur',
    'Uttar Pradesh',
    'Sivaganga',
    'Sivagangai SeemaiTamil Nadu',
    'Sivasagar',
    'Assam',
    'Siwan',
    'Bihar',
    'Solan',
    'Himachal Pradesh',
    'Solapur',
    'Maharashtra',
    'Sonbhadra',
    'Uttar Pradesh',
    'Sonipat',
    'Ganaur',
    'Gohana',
    'Sonepat',
    'Haryana',
    'Sonitpur',
    'Assam',
    'South 24 Parganas',
    '24 south parganasWest Bengal',
    'South Andaman',
    'Port Blair',
    'Andaman',
    'Andaman and Nicobar Islands',
    'South Delhi',
    'Dhaulakuan',
    'Lado Sarai',
    'Chatarpur',
    'Pushp Vihar',
    'Delhi',
    'South District',
    'Sikkim South District',
    'Sikkim South',
    'Sikkim',
    'South East Delhi',
    'Nizamuddin',
    'Lajpath Nagar',
    'Tuglakabad',
    'Badarpur',
    'South Ex',
    'Safdarjung',
    'Delhi',
    'South Garo Hills',
    'Meghalaya',
    'South Goa',
    'Goa',
    'South Salmara Mancachar',
    'Assam',
    'South Tripura',
    'Tripura',
    'South West Delhi',
    'Bijwasan',
    'Kapashera',
    'Palam',
    'Najafgarh',
    'Delhi',
    'South West Garo Hills',
    'Meghalaya',
    'South West Khasi Hills',
    'Meghalaya',
    'Sri Muktsar Sahib',
    'Muktsar',
    'Muktasar',
    'Punjab',
    'Srikakulam',
    'ChicacoleAndhra Pradesh',
    'Srinagar',
    'Jammu and Kashmir',
    'Subarnapur',
    'Odisha',
    'Sukma',
    'Chhindgarh',
    'Konta',
    'Sukma',
    'Chhattisgarh',
    'Sultanpur',
    'Uttar Pradesh',
    'Sundargarh',
    'rourkelaOdisha',
    'Supaul',
    'Bihar',
    'Surajpur',
    'Bishrampur',
    'Odagi',
    'Pratappur',
    'Prem Nagar',
    'Ramanuj Nagar',
    'Surajpur',
    'Chhattisgarh',
    'Surat',
    'Gujarat',
    'Surendranagar',
    'WadhwanGujarat',
    'Surguja',
    'Ambikapur',
    'Namna Kalan',
    'Phunderdihari',
    'Sitapur',
    'Telgaon',
    'Chhattisgarh',
    'Suryapet',
    'Telangana',
    'Tamenglong',
    'Manipur',
    'Tapi',
    'Vyara',
    'Songadh',
    'Nijhar',
    'Valod',
    'Uchhal',
    'Dolavan',
    'Kukarmunda',
    'Gujarat',
    'Tarn Taran',
    'Punjab',
    'Tawang',
    'Arunachal Pradesh',
    'Tehri Garhwal',
    'Ghanshali',
    'Deoprayag',
    'Tehri',
    'Dhanolti',
    'Uttarakhand',
    'Tengnoupal',
    'Manipur',
    'Thane',
    'Maharashtra',
    'Thanjavur',
    'TanjoreTamil Nadu',
    'The Dangs',
    'Subir',
    'Waghal',
    'Ahwa',
    'dang',
    'Gujarat',
    'The Nilgiris',
    'Nilgiri',
    'ooty',
    'Tamil Nadu',
    'Theni',
    'Tamil Nadu',
    'Thiruvallur',
    'Thiru evvulTamil Nadu',
    'Thiruvananthapuram',
    'Kerala',
    'Thiruvarur',
    'TiruvarurTamil Nadu',
    'Thoothukkudi',
    'TuticorinTamil Nadu',
    'Thoubal',
    'Manipur',
    'Thrissur',
    'Kerala',
    'Tikamgarh',
    'Madhya Pradesh',
    'Tinsukia',
    'Assam',
    'Tirap',
    'KhonsaArunachal Pradesh',
    'Tiruchirappalli',
    'Trichinopoly',
    'Trichy',
    'Tiruchi',
    'Tamil Nadu',
    'Tirunelveli',
    'Tenkasi district has been bifurcated from this districtTamil Nadu',
    'Tiruppur',
    'TirupurTamil Nadu',
    'Tiruvannamalai',
    'ArunaiTamil Nadu',
    'Tonk',
    'Rajasthan',
    'Tuensang',
    'Nagaland',
    'Tumakuru',
    'Karnataka',
    'Udaipur',
    'Rajasthan',
    'Udalguri',
    'Assam',
    'Udham Singh Nagar',
    'RudrapurUttarakhand',
    'Udhampur',
    'Jammu and Kashmir',
    'Udupi',
    'Karnataka',
    'Ujjain',
    'Nagda',
    'Badnagar',
    '',
    'Madhya Pradesh',
    'Ukhrul',
    'Manipur',
    'Umaria',
    'Madhya Pradesh',
    'Una',
    'Himachal Pradesh',
    'Unnao',
    'Uttar Pradesh',
    'Unokoti',
    'Tripura',
    'Upper Dibang Valley',
    'AniniArunachal Pradesh',
    'Upper Siang',
    'YingkiongArunachal Pradesh',
    'Upper Subansiri',
    'DaporijoArunachal Pradesh',
    'Uttar Bastar Kanker',
    'Antagarh',
    'Bhanupratappur',
    'Charama',
    'Kanker',
    'Narharpur',
    'Pakhanjur',
    'Chhattisgarh',
    'Uttar Dinajpur',
    'West Bengal',
    'Uttara Kannada',
    'Karnataka',
    'Uttarkashi',
    'Purola',
    'Yamunotri',
    'Gangotri',
    'Uttarakhand',
    'Vadodara',
    'Dabhoi',
    'Karjan',
    'Padra',
    'Savli',
    'Sinor',
    'Waghodia',
    'Gujarat',
    'Vaishali',
    'Bihar',
    'Valsad',
    'Pardi',
    'Vapi',
    'Dharampur',
    'Kaparada',
    'Umbergaon',
    'Gujarat',
    'Varanasi',
    'Banaras',
    'Benaras',
    'Kashi',
    'Uttar Pradesh',
    'Vellore',
    'Vellur',
    'Tamil Nadu',
    'Vidisha',
    'Madhya Pradesh',
    'Vijayapura',
    'Karnataka',
    'Vikarabad',
    'Telangana',
    'Viluppuram',
    'Kallakurichi ',
    'Virudhunagar',
    'VirudupattiTamil Nadu',
    'Visakhapatnam',
    'VizagapatamAndhra Pradesh',
    'Vizianagaram',
    'VijayanagaramAndhra Pradesh',
    'Wanaparthy',
    'Telangana',
    'Warangal Rural',
    'GeesugondaTelangana',
    'Warangal Urban',
    'Warangal city',
    'warangal',
    'Telangana',
    'Wardha',
    'Maharashtra',
    'Washim',
    'Maharashtra',
    'Wayanad',
    'Kerala',
    'West Champaran',
    'Bihar',
    'West Delhi',
    'Punjabi Bagh',
    'Paschim Vihar',
    'Janakpuri',
    'Kirti Nagar',
    'Delhi',
    'West District',
    'Sikkim West District',
    'Sikkim West',
    'Sikkim',
    'West Garo Hills',
    'Meghalaya',
    'West Godavari',
    'Paschima Godavari Jilla',
    'Eluru',
    'Andhra Pradesh',
    'West Jaintia Hills',
    'Meghalaya',
    'West Kameng',
    'BomdilaArunachal Pradesh',
    'West Karbi Anglong',
    'Assam',
    'West Khasi Hills',
    'Meghalaya',
    'West Siang',
    'Aalo',
    'Along',
    'Arunachal Pradesh',
    'West Tripura',
    'Tripura',
    'Wokha',
    'Nagaland',
    'Y.S.R.',
    'Kadapa',
    'Cuddapah',
    'Andhra Pradesh',
    'Yadadri Bhuvanagiri',
    'BhongiriTelangana',
    'Yadgir',
    'Karnataka',
    'Yamunanagar',
    'Jagadhri',
    'Chhachhrauli',
    'Sadhaura',
    'Adi Badri',
    'Bilaspur',
    'Radaur',
    'Haryana',
    'Yanam',
    'Puducherry',
    'Yavatmal',
    'Maharashtra',
    'Zunheboto',
    'Nagaland',
  ],
  'en-IN': [
    'active',
    'recovered',
    'deceased',
    'confirmed',
    'cases',
    'dead',
    'death',
    'died',
    'India',
    'active cases',
    'recovered cases',
    'deceased cases',
    'confirmed cases',
    'Adilabad',
    'Telangana',
    'Agar Malwa',
    'Madhya Pradesh',
    'Agra',
    'Uttar Pradesh',
    'Ahmadabad',
    'AmdavadGujarat',
    'Ahmadnagar',
    'Ahmednagar',
    'Ahmednagar',
    'Maharashtra',
    'Aizawl',
    'Mizoram',
    'Ajmer',
    'Rajasthan',
    'Akola',
    'Maharashtra',
    'Alappuzha',
    'Kerala',
    'Aligarh',
    'Uttar Pradesh',
    'Alipurduar',
    'alipurdwarWest Bengal',
    'Alirajpur',
    'Madhya Pradesh',
    'Almora',
    'Dwarahat',
    'Ranikhet',
    'Someshwar',
    'Jageshwar',
    'Uttarakhand',
    'Alwar',
    'Rajasthan',
    'Ambala',
    'Mulana',
    'Naraingarh',
    'Haryana',
    'Ambedkar Nagar',
    'AkbarpurUttar Pradesh',
    'Amethi',
    'Uttar Pradesh',
    'Amravati',
    'Maharashtra',
    'Amreli',
    'Anumanji',
    'Amlik',
    'Amravat',
    'Gujarat',
    'Amritsar',
    'Punjab',
    'Amroha',
    'Jyotiba Phule Nagar',
    'Azizpura',
    'Uttar Pradesh',
    'Anand',
    'Khambhat',
    'Karamsad',
    'Tarapur',
    'Petlad',
    'Sojitra',
    'Gujarat',
    'Anantapur',
    'Anantapuramu',
    'Hindupur',
    'Andhra Pradesh',
    'Anantnag',
    'Jammu and Kashmir',
    'Anjaw',
    'HawaiArunachal Pradesh',
    'Anugul',
    'Odisha',
    'Anuppur',
    'Madhya Pradesh',
    'Araria',
    'Bihar',
    'Aravalli',
    'Aravalli',
    'Modasa',
    'Gujarat',
    'Ariyalur',
    'Tamil Nadu',
    'Arwal',
    'Bihar',
    'Ashoknagar',
    'Madhya Pradesh',
    'Auraiya',
    'Kannauj',
    'Etawah',
    'Uttar Pradesh',
    'Aurangabad',
    'Bihar',
    'Aurangabad',
    'Maharashtra',
    'Azamgarh',
    'AzamgadhUttar Pradesh',
    'Badgam',
    'Jammu and Kashmir',
    'Bagalkote',
    'Karnataka',
    'Bageshwar',
    'Uttarakhand',
    'Baghpat',
    'Uttar Pradesh',
    'Bahraich',
    'Uttar Pradesh',
    'Baksa',
    'Assam',
    'Balaghat',
    'Madhya Pradesh',
    'Balangir',
    'Odisha',
    'Baleshwar',
    'Odisha',
    'Ballari',
    'Karnataka',
    'Ballia',
    'Uttar Pradesh',
    'Balod',
    'Dalli RajharaChhattisgarh',
    'Baloda Bazar',
    'BhataparaChhattisgarh',
    'Balrampur',
    'Kusmi',
    'Rajpur',
    'Ramanujganj',
    'Ramchandarpur',
    'Shankargarh',
    'Wadrafnagar',
    'Chhattisgarh',
    'Balrampur',
    'Uttar Pradesh',
    'Bametara',
    'Bametara',
    'Nawagarh',
    'Saja',
    'Chhattisgarh',
    'Banas Kantha',
    'banaskanthaGujarat',
    'Banda',
    'Uttar Pradesh',
    'Bandipore',
    'Jammu and Kashmir',
    'Banka',
    'Bihar',
    'Bankura',
    'West Bengal',
    'Banswara',
    'Rajasthan',
    'Bara Banki',
    'BarabankiUttar Pradesh',
    'Baramula',
    'Jammu and Kashmir',
    'Baran',
    'Rajasthan',
    'Bareilly',
    'Uttar Pradesh',
    'Bargarh',
    'Odisha',
    'Barmer',
    'Rajasthan',
    'Barnala',
    'Punjab',
    'Barpeta',
    'Assam',
    'Barwani',
    'Madhya Pradesh',
    'Bastar',
    'Darba',
    'Frezarpur',
    'Hatkachora',
    'Jagdalpur',
    'Jagdalpur',
    'Sosanpal',
    'Chhattisgarh',
    'Basti',
    'Uttar Pradesh',
    'Bathinda',
    'Punjab',
    'Baudh',
    'Odisha',
    'Begusarai',
    'Bihar',
    'Belagavi',
    'Karnataka',
    'Bengaluru',
    'Karnataka',
    'Bengaluru Rural',
    'Karnataka',
    'Betul',
    'Madhya Pradesh',
    'Bhadohi',
    'Uttar Pradesh',
    'Bhadradri Kothagudem',
    'KothagudemTelangana',
    'Bhadrak',
    'Odisha',
    'Bhagalpur',
    'Bihar',
    'Bhandara',
    'Maharashtra',
    'Bharatpur',
    'Rajasthan',
    'Bharuch',
    'broach',
    'Amirgadh',
    'Bhabhar',
    'Dantiwada',
    'Danta',
    'Deesa',
    'Deodar',
    'Dhanera',
    'Palanpur',
    'Sihori (Kankrej)',
    'Tharad',
    'Vadgam',
    'Lakhni',
    'Suigam',
    'Vav',
    'Gujarat',
    'Bhavnagar',
    'Bhavnagar',
    'Sihor',
    'Umrala',
    'Gariadhar',
    'Palitana',
    'Mahuva',
    'Talaja',
    'Ghogha',
    'Jesar',
    'Vallbhipur.',
    'Gujarat',
    'Bhilwara',
    'Rajasthan',
    'Bhind',
    'Madhya Pradesh',
    'Bhiwani',
    'Bhiwani',
    'Loharu',
    'Siwani',
    'Tosham',
    'Haryana',
    'Bhojpur',
    'ArrahBihar',
    'Bhopal',
    'Madhya Pradesh',
    'Bid',
    'Beed',
    'Beed',
    'Maharashtra',
    'Bidar',
    'Karnataka',
    'Bijapur',
    'Bijapur',
    'Bhopalpatnam',
    'Chhattisgarh',
    'Bijnor',
    'Uttar Pradesh',
    'Bikaner',
    'Rajasthan',
    'Bilaspur',
    'Baitalpur',
    'Bilha',
    'Bodri',
    'Deori',
    'Gaurella',
    'Ghutku',
    'Kota',
    'Lingiyadih',
    'Mehmand',
    'Pendra',
    'Ratanpur',
    'Sirgiti',
    'Takhatpur',
    'Chhattisgarh',
    'Bilaspur',
    'Himachal Pradesh',
    'Birbhum',
    'West Bengal',
    'Bishnupur',
    'Manipur',
    'Biswanath',
    'Biswanath Chariali',
    '',
    'Assam',
    'Bokaro',
    'Jharkhand',
    'Bongaigaon',
    'Assam',
    'Botad',
    'Bitad',
    'Gadhada',
    'Barvala',
    'Ranpur',
    'Gujarat',
    'Budaun',
    'Uttar Pradesh',
    'Bulandshahr',
    'Bulandshahar',
    'Khurja',
    'Uttar Pradesh',
    'Buldana',
    'BuldhanaMaharashtra',
    'Bundi',
    'Rajasthan',
    'Burhanpur',
    'Madhya Pradesh',
    'Buxar',
    'BalliaBihar',
    'Cachar',
    'Assam',
    'Central Delhi',
    'Cannaught Place',
    'CP',
    '',
    'Delhi',
    'Chamarajanagara',
    'Karnataka',
    'Chamba',
    'Himachal Pradesh',
    'Chamoli',
    'Badrinath',
    'Karnprayag',
    'Tharali',
    'Uttarakhand',
    'Champawat',
    'Uttarakhand',
    'Champhai',
    'Mizoram',
    'Chandauli',
    'Uttar Pradesh',
    'Chandel',
    'Manipur',
    'Chandigarh',
    'Chandigarh',
    'Chandrapur',
    'Maharashtra',
    'Changlang',
    'Arunachal Pradesh',
    'Charaideo',
    'Assam',
    'Charki Dadri',
    'BadhraHaryana',
    'Chatra',
    'Jharkhand',
    'Chennai',
    'Tamil Nadu',
    'Chhatarpur',
    'Madhya Pradesh',
    'Chhindwara',
    'Madhya Pradesh',
    'Chikkaballapura',
    'Karnataka',
    'Chikkamagaluru',
    'Karnataka',
    'Chirang',
    'Assam',
    'Chitradurga',
    'Karnataka',
    'Chitrakoot',
    'Uttar Pradesh',
    'Chittaurgarh',
    'Rajasthan',
    'Chittoor',
    'Andhra Pradesh',
    'Chota Udaipur',
    'Chhota Udepur',
    'Pavi Jetpur',
    'Kawant',
    'Naswadi',
    'Sankheda',
    'Bodeli',
    'Gujarat',
    'Churachandpur',
    'Manipur',
    'Churu',
    'Rajasthan',
    'Coimbatore',
    'Tamil Nadu',
    'Cooch Behar',
    'Coochbehar',
    'Koch Bihar',
    'West Bengal',
    'Cuddalore',
    'Tamil Nadu',
    'Cuttack',
    'Odisha',
    'Dadra and Nagar Haveli',
    'Dadra and Nagar Haveli',
    'Dakshin Bastar Dantewada',
    'Bade Bacheli',
    'Dantewada',
    'Geedam',
    'Katekalyan',
    'Kirandul',
    'Kuwakonda',
    'Penta',
    'Chhattisgarh',
    'Dakshin Dinajpur',
    'South DinajpurWest Bengal',
    'Dakshina Kannada',
    'Karnataka',
    'Daman',
    'Daman And Diu',
    'Damoh',
    'Madhya Pradesh',
    'Darbhanga',
    'Bihar',
    'Darjeeling',
    'West Bengal',
    'Darrang',
    'Assam',
    'Datia',
    'Madhya Pradesh',
    'Dausa',
    'Rajasthan',
    'Davanagere',
    'Karnataka',
    'Debagarh',
    'Odisha',
    'Dehradun',
    'Mussoorie',
    'Rishikesh',
    'Uttarakhand',
    'Deoghar',
    'Jharkhand',
    'Deoria',
    'Uttar Pradesh',
    'Devbhumi Dwarka',
    'Dwarka',
    'Bhanvad',
    'Kalyanpur',
    'Khambaila',
    'Gujarat',
    'Dewas',
    'Madhya Pradesh',
    'Dhalai',
    'Tripura',
    'Dhamtari',
    'Bagoud',
    ' Kurud',
    'Nagri',
    'Dhamtari',
    'Chhattisgarh',
    'Dhanbad',
    'Jharkhand',
    'Dhar',
    'PithampurMadhya Pradesh',
    'Dharmapuri',
    'dharmapuriTamil Nadu',
    'Dharwad',
    'Karnataka',
    'Dhaulpur',
    'Rajasthan',
    'Dhemaji',
    'Assam',
    'Dhenkanal',
    'Odisha',
    'Dhubri',
    'Assam',
    'Dhule',
    'Maharashtra',
    'Dibrugarh',
    'Assam',
    'Dima Hasao',
    'Assam',
    'Dimapur',
    'Nagaland',
    'Dindigul',
    'Tamil Nadu',
    'Dindori',
    'Madhya Pradesh',
    '',
    '',
    'Diu',
    'Daman And Diu',
    'Doda',
    'Jammu and Kashmir',
    'Dohad',
    'Dahod',
    'Jhalod',
    'Devgarh',
    'Garbada',
    'Limkheda',
    'Fatehpur',
    'Dhanpur',
    'Sanjeli',
    'Gujarat',
    'Dumka',
    'Jharkhand',
    'Dungarpur',
    'Rajasthan',
    'Durg',
    'Bhilai',
    ' Durg',
    ' Ahiwara',
    'Bhilai Charoda',
    'Dhamdha',
    'Jamul',
    'Khamhria',
    'Kumhari',
    'Mahamaya',
    'Parpodi',
    'Patan',
    'Chhattisgarh',
    'East Champaran',
    'Bihar',
    'East Delhi',
    'Dilshad Garden',
    'Mayur vihar',
    'Parpatganj',
    'Delhi',
    'East District',
    'Sikkim East District',
    'Sikkim East',
    'Sikkim',
    'East Garo Hills',
    'Meghalaya',
    'East Godavari',
    'KakinadaAndhra Pradesh',
    'East Jaintia Hills',
    'Meghalaya',
    'East Kameng',
    'SeppaArunachal Pradesh',
    'East Khasi Hills',
    'Meghalaya',
    'East Siang',
    'PasighatArunachal Pradesh',
    'Ernakulam',
    'Kerala',
    'Erode',
    'Tamil Nadu',
    'Etah',
    'Uttar Pradesh',
    'Etawah',
    'Uttar Pradesh',
    'Faizabad',
    'AyodhyaUttar Pradesh',
    'Faridabad',
    'Nuh',
    'Palwal',
    'Haryana',
    'Faridkot',
    'Punjab',
    'Farrukhabad',
    'FategarhUttar Pradesh',
    'Fatehabad',
    'Ratia',
    'Tohana',
    'Haryana',
    'Fatehgarh Sahib',
    'Punjab',
    'Fatehpur',
    'Uttar Pradesh',
    'Fazilka',
    'AboharPunjab',
    'Firozabad',
    'ShikohabadUttar Pradesh',
    'Firozpur',
    'Punjab',
    'Gadag',
    'Karnataka',
    'Gadchiroli',
    'Maharashtra',
    'Gajapati',
    'Odisha',
    'Ganderbal',
    'Jammu and Kashmir',
    'Gandhinagar',
    'Motera',
    'Adala',
    'Kalol INA',
    'Dahegam',
    'Mansa',
    'Gujarat',
    'Ganganagar',
    'Rajasthan',
    'Ganjam',
    'BerhampurOdisha',
    'Garhwa',
    'Jharkhand',
    'Gariaband',
    'GariabandChhattisgarh',
    'Gautam Buddha Nagar',
    'Noida',
    'Greater Noida',
    'Uttar Pradesh',
    'Gaya',
    'Bihar',
    'Ghaziabad',
    'ModinagarUttar Pradesh',
    'Ghazipur',
    'Uttar Pradesh',
    'Gir Somnath',
    'Veraval',
    'Talala',
    'Sutrapada',
    'Kodinar',
    'Una',
    'Gir-Gadhada',
    'Gujarat',
    'Giridih',
    'Jharkhand',
    'Goalpara',
    'Assam',
    'Godda',
    'Jharkhand',
    'Golaghat',
    'Assam',
    'Gomati',
    'Tripura',
    'Gonda',
    'Uttar Pradesh',
    'Gondiya',
    'GondiaMaharashtra',
    'Gopalganj',
    'Bihar',
    'Gorakhpur',
    'Uttar Pradesh',
    'Gumla',
    'Jharkhand',
    'Guna',
    'Madhya Pradesh',
    'Guntur',
    'Andhra Pradesh',
    'Gurdaspur',
    'BatalaPunjab',
    'Gurugram',
    'Sohna',
    'Pataudi',
    'Farukh Nagar',
    'Manesar',
    'gurgaon',
    'Haryana',
    'Gwalior',
    'Madhya Pradesh',
    'Hailakandi',
    'Assam',
    'Hamirpur',
    'Himachal Pradesh',
    'Hamirpur',
    'Uttar Pradesh',
    'Hanumangarh',
    'Rajasthan',
    'Hapur',
    'Uttar Pradesh',
    'Harda',
    'Madhya Pradesh',
    'Hardoi',
    'Uttar Pradesh',
    'Haridwar',
    'RoorkeeUttarakhand',
    'Hassan',
    'Karnataka',
    'Hathras',
    'Uttar Pradesh',
    'Haveri',
    'Karnataka',
    'Hazaribagh',
    'Jharkhand',
    'Hingoli',
    'Maharashtra',
    'Hisar',
    'Adampur',
    'Agroha',
    'Barwala',
    'Hansi',
    'Narnaund',
    'Uklanamandi',
    'Haryana',
    'Hojai',
    'Assam',
    'Hooghly',
    'Hoogli',
    'Hugli',
    'West Bengal',
    'Hoshangabad',
    'ItarsiMadhya Pradesh',
    'Hoshiarpur',
    'Punjab',
    'Howrah',
    'West Bengal',
    'Hyderabad',
    'Telangana',
    'Idukki',
    'Kerala',
    'Imphal East',
    'Manipur',
    'Imphal West',
    'Manipur',
    'Indore',
    'Madhya Pradesh',
    'Jabalpur',
    'Madhya Pradesh',
    'Jagatsinghapur',
    'Odisha',
    'Jagitial',
    'Telangana',
    'Jaipur',
    'Rajasthan',
    'Jaisalmer',
    'Rajasthan',
    'Jajapur',
    'Odisha',
    'Jalandhar',
    'Punjab',
    'Jalaun',
    'OraiUttar Pradesh',
    'Jalgaon',
    'BhusawalMaharashtra',
    'Jalna',
    'Maharashtra',
    'Jalore',
    'Rajasthan',
    'Jalpaiguri',
    'West Bengal',
    'Jammu',
    'Jammu and Kashmir',
    'Jamnagar',
    'Jam Jodhpur',
    'Jodiya',
    'DhrolJamnagar',
    'Lalpur',
    'Kalavad',
    'Gujarat',
    'Jamtara',
    'Jharkhand',
    'Jamui',
    'Bihar',
    'Jangoan',
    'Telangana',
    'Janjgir Champa',
    'Adbhar',
    'Akaltara',
    'Baloda',
    'Champa',
    'Janjgir',
    'Kharod',
    'Naila-Janjgir',
    'Naya Baradwar',
    'Pamgarh',
    'Sakti',
    'Shivrinarayan',
    'Chhattisgarh',
    'Jashpur',
    'Jashpur Nagar',
    'Kunkuri',
    'Pathalgaon',
    'Chhattisgarh',
    'Jaunpur',
    'Uttar Pradesh',
    'Jayashankar',
    'Bhupalpalle',
    'Jayashankar Bhupalpally',
    'Telangana',
    'Jehanabad',
    'Bihar',
    'Jhabua',
    'Madhya Pradesh',
    'Jhajjar',
    'Bahadurgarh',
    'Badli',
    'Beri',
    'Haryana',
    'Jhalawar',
    'Rajasthan',
    'Jhansi',
    'Uttar Pradesh',
    'Jhargram',
    'West Bengal',
    'Jharsuguda',
    'Odisha',
    'Jhunjhunu',
    'Rajasthan',
    'Jind',
    'Narwana',
    'Safidon',
    'Haryana',
    'Jiribam',
    'Manipur',
    'Jodhpur',
    'Rajasthan',
    'Jogulamba Gadwal',
    'GadwalTelangana',
    'Jorhat',
    'Assam',
    'Junagadh',
    'Junagadh',
    'Bhesan',
    'Junagadhl',
    'Keshod',
    'Malia',
    'Manavadar',
    'Mangrol',
    'Mendarda',
    'Vanthali',
    'Visavadar',
    'Gujarat',
    'Kabeerdham',
    'Kabirdham',
    'Chilpi',
    'Kawardha',
    'Pandariya',
    'Pandatarai',
    'Chhattisgarh',
    'Kachchh',
    'Abdasa',
    'Anjar',
    'Bhachau',
    'Bhuj',
    'Gandhidham',
    'Lakhpat',
    'Mandvi',
    'Mundra',
    'Nakhatrana',
    'Rapar',
    'Gujarat',
    'Kaimur Bhabua',
    'Bihar',
    'Kaithal',
    'Guhla',
    'Pundri',
    'Kalayat',
    'Haryana',
    'Kakching',
    'Manipur',
    'Kalaburagi',
    'GulbargaKarnataka',
    'Kalahandi',
    'bhawanipatnaOdisha',
    'Kalimpong',
    'West Bengal',
    'Kamareddy',
    'Telangana',
    'Kamjong',
    'Manipur',
    'Kamle',
    'Khamle',
    'Raga',
    'Arunachal Pradesh',
    'Kamrup',
    'Assam',
    'Kamrup Metropolitan',
    'GuwahatiAssam',
    'Kancheepuram',
    'KanchipuramTamil Nadu',
    'Kandhamal',
    'Odisha',
    'Kangpokpi',
    'Manipur',
    'Kangra',
    'Himachal Pradesh',
    'Kanker',
    'Bhanupratappur',
    'Kapsi',
    'Pakhanjore',
    '',
    'Kannauj',
    'Uttar Pradesh',
    'Kanniyakumari',
    'KanyakumariTamil Nadu',
    'Kannur',
    'Kerala',
    'Kanpur Dehat',
    'Uttar Pradesh',
    'Kanpur Nagar',
    'Kanpur city',
    'Kanpur',
    'Uttar Pradesh',
    'Kapurthala',
    'PhagwaraPunjab',
    'Karaikal',
    'Puducherry',
    'Karauli',
    'Rajasthan',
    'Karbi Anglong',
    'Assam',
    'Kargil',
    'Ladakh',
    'Karimganj',
    'Assam',
    'Karimnagar',
    'Telangana',
    'Karnal',
    'Nilokheri',
    'Indri',
    'Gharaunda',
    'Assandh',
    'Haryana',
    'Karur',
    'Tamil Nadu',
    'Kasaragod',
    'Kerala',
    'Kasganj',
    'Uttar Pradesh',
    'Kathua',
    'Jammu and Kashmir',
    'Katihar',
    'Bihar',
    'Katni',
    'MurwaraMadhya Pradesh',
    'Kaushambi',
    'Uttar Pradesh',
    'Kendrapara',
    'Odisha',
    'Kendujhar',
    'Odisha',
    'Khagaria',
    'Bihar',
    'Khammam',
    'Telangana',
    'Khandwa',
    'East NimarMadhya Pradesh',
    'Khargone',
    'West NimarMadhya Pradesh',
    'Kheda',
    'Nadiad',
    'Thasra',
    'Kapadvanj',
    'Mehmedabad',
    'Kathlal',
    'Matar',
    'Mahudha',
    'Kaira',
    'Gujarat',
    'Kheri',
    'Lakhimpur KheriUttar Pradesh',
    'Khordha',
    'BhubhaneshwarOdisha',
    'Khowai',
    'Tripura',
    'Khunti',
    'Jharkhand',
    'Kinnaur',
    'Himachal Pradesh',
    'Kiphire',
    'Nagaland',
    'Kishanganj',
    'Bihar',
    'Kishtwar',
    'Jammu and Kashmir',
    'Kodagu',
    'coorgKarnataka',
    'Kodarma',
    'Jharkhand',
    'Kohima',
    'Nagaland',
    'Kokrajhar',
    'Assam',
    'Kolar',
    'Karnataka',
    'Kolasib',
    'Mizoram',
    'Kolhapur',
    'Maharashtra',
    'Kolkata',
    'CalcuttaWest Bengal',
    'Kollam',
    'Kerala',
    'Kondagaon',
    'Keskal',
    'Pharasgaon',
    'Chhattisgarh',
    'Koppal',
    'Karnataka',
    'Koraput',
    'Odisha',
    'Korba',
    'Banki Mongra',
    'Dipka',
    'Katghora',
    'Korba',
    'Rajgamar',
    'Chhattisgarh',
    'Koriya',
    'Baikunthpur',
    'Koriya',
    'Chharchha',
    'Chirmiri',
    'Jhagrakhand',
    'Khongapani',
    'Manendragarh',
    'Chhattisgarh',
    'Kota',
    'Rajasthan',
    'Kottayam',
    'Kerala',
    'Kozhikode',
    'Kerala',
    'Kra Daadi',
    'New Palin',
    'Jamin',
    'Arunachal Pradesh',
    'Krishna',
    'Vijayawada',
    'Machilipatnam',
    'Andhra Pradesh',
    'Krishnagiri',
    'Tamil Nadu',
    'Kulgam',
    'Jammu and Kashmir',
    'Kullu',
    'Himachal Pradesh',
    'Kumuram Bheem Asifabad',
    'AsifabadTelangana',
    'Kupwara',
    'Jammu and Kashmir',
    'Kurnool',
    'Andhra Pradesh',
    'Kurukshetra',
    'Thanesar',
    'Pehowa',
    'Haryana',
    'Kurung Kumey',
    'KoloriangArunachal Pradesh',
    'Kushinagar',
    'Uttar Pradesh',
    'Lahul and Spiti',
    'Himachal Pradesh',
    'Lakhimpur',
    'Assam',
    'Lakhisarai',
    'Bihar',
    'Lakshadweep',
    'Lakshadweep',
    'Lalitpur',
    'Uttar Pradesh',
    'Latehar',
    'Jharkhand',
    'Latur',
    'Maharashtra',
    'Lawngtlai',
    'Mizoram',
    'Leh',
    'Ladakh',
    'Lepa Rada',
    'BasarArunachal Pradesh',
    'Lohardaga',
    'Jharkhand',
    'Lohit',
    'TezuArunachal Pradesh',
    'Longding',
    'Arunachal Pradesh',
    'Longleng',
    'Nagaland',
    'Lower Dibang Valley',
    'RoingArunachal Pradesh',
    'Lower Siang',
    'LikabaliArunachal Pradesh',
    'Lower Subansiri',
    'ZiroArunachal Pradesh',
    'Lucknow',
    'Uttar Pradesh',
    'Ludhiana',
    'Punjab',
    'Lunglei',
    'Mizoram',
    'Madhepura',
    'Bihar',
    'Madhubani',
    'Bihar',
    'Madurai',
    'Tamil Nadu',
    'Mahabubabad',
    'Telangana',
    'Mahabubnagar',
    'Telangana',
    'Mahasamund',
    'Bagbahara',
    'Basna',
    'Mahasamund',
    'Pithora',
    'Saraipali',
    'Sirpur',
    'Chhattisgarh',
    'Mahe',
    'Puducherry',
    'Mahendragarh',
    'Narnaul',
    'Nangal Chowdhary',
    'Kanina Mahendragarh',
    'Ateli',
    'Haryana',
    'Mahesana',
    'Vijapur',
    'Bahucharaji',
    'Satlasana',
    'Modhera',
    'Unjha',
    'Vadnagar',
    'Kalol',
    'Kadi',
    'Visnagar',
    'Kherva',
    'Jotana',
    'Kheralu',
    'Gujarat',
    'Mahisagar',
    'Balasinor',
    'Lunavada',
    'Kadana',
    'Virpur',
    'Santrampur',
    'Khanpur',
    'Gujarat',
    'Mahoba',
    'Uttar Pradesh',
    'Mahrajganj',
    'Uttar Pradesh',
    'Mainpuri',
    'Uttar Pradesh',
    'Majuli',
    'Assam',
    'Malappuram',
    'Kerala',
    'Maldah',
    'Malda',
    'Maldaha',
    'West Bengal',
    'Malkangiri',
    'Odisha',
    'Mamit',
    'Mizoram',
    'Mancherial',
    'Telangana',
    'Mandi',
    'Himachal Pradesh',
    'Mandla',
    'Madhya Pradesh',
    'Mandsaur',
    'Madhya Pradesh',
    'Mandya',
    'Karnataka',
    'Mansa',
    'Punjab',
    'Mathura',
    'Vrindavan',
    'Mathura Vrindavan',
    'Uttar Pradesh',
    'Mau',
    'Uttar Pradesh',
    'Mayurbhanj',
    'baripadaOdisha',
    'Medak',
    'Telangana',
    'Medchal Malkajgiri',
    'Telangana',
    'Medinipur East',
    'Purba Medinipur',
    'East Medinipur',
    'East Midnapore',
    'Midnapore East',
    'West Bengal',
    'Medinipur West',
    'Paschim Medinipur',
    'West Midnapore',
    'Midnapore West',
    'West Bengal',
    'Meerut',
    'Uttar Pradesh',
    'Mirpur',
    'Jammu and Kashmir',
    'Mirzapur',
    'Uttar Pradesh',
    'Moga',
    'Punjab',
    'Mokokchung',
    'Nagaland',
    'Mon',
    'Nagaland',
    'Moradabad',
    'Uttar Pradesh',
    'Morbi',
    'Maliya',
    'Tankara',
    'Wankaner',
    'Rajkot',
    'Halvad ',
    'Gujarat',
    'Morena',
    'Madhya Pradesh',
    'Morigaon',
    'Assam',
    'Mulugu',
    'Telangana',
    'Mumbai',
    'BombayMaharashtra',
    'Mumbai Suburban',
    'Maharashtra',
    'Mungeli',
    'Lormi',
    'Mungeli',
    'Chhattisgarh',
    'Munger',
    'Bihar',
    'Murshidabad',
    'West Bengal',
    'Muzaffarabad',
    'Jammu and Kashmir',
    'Muzaffarnagar',
    'Uttar Pradesh',
    'Muzaffarpur',
    'Bihar',
    'Mysuru',
    'Karnataka',
    'Nabarangapur',
    'Odisha',
    'Nadia',
    'West Bengal',
    'Nagaon',
    'Assam',
    'Nagapattinam',
    'Mayiladuthurai',
    'Nagapatnam',
    'Tamil Nadu',
    'Nagarkurnool',
    'Telangana',
    'Nagaur',
    'Rajasthan',
    'Nagpur',
    'Maharashtra',
    'Nainital',
    'Haldwani',
    'Lalkua',
    'Bhimtal',
    'Kaladhungi',
    'Ramnagar',
    'Uttarakhand',
    'Nalanda',
    'Bihar',
    'Nalbari',
    'Assam',
    'Nalgonda',
    'Telangana',
    'Namakkal',
    'Tamil Nadu',
    'Namsai',
    'Arunachal Pradesh',
    'Nanded',
    'Maharashtra',
    'Nandurbar',
    'Maharashtra',
    'Narayanpet',
    'Telangana',
    'Narayanpur',
    'NarayanpurChhattisgarh',
    'Narmada',
    'Tilakwada',
    'Garudeshwar',
    'Nandod',
    'Dediyapada',
    'Sagbara.',
    'Gujarat',
    'Narsimhapur',
    'Madhya Pradesh',
    'Nashik',
    'Maharashtra',
    'Navsari',
    'Jalalpore',
    'Gandevi',
    'Chikhli',
    'Khergam',
    'Bansda',
    'Gujarat',
    'Nawada',
    'Bihar',
    'Nayagarh',
    'Odisha',
    'Neemuch',
    'Madhya Pradesh',
    'New Delhi',
    'Delhi',
    'Dilli',
    'Purani Dilli',
    'Old delhi',
    'Delhi',
    'Nicobars',
    'Carnicobar',
    'Campbell Bay',
    'Indira point',
    'Andaman and Nicobar Islands',
    'Nirmal',
    'Telangana',
    'Niwari',
    'Madhya Pradesh',
    'Nizamabad',
    'Telangana',
    'Noney',
    'Manipur',
    'North 24 Parganas',
    '24 paraganas northWest Bengal',
    'North and Middle Andaman',
    'DiglipurAndaman and Nicobar Islands',
    'North Delhi',
    'Rohini',
    'Narela',
    'Delhi',
    'North District',
    'Sikkim North District',
    'Sikkim North',
    'Sikkim',
    'North East Delhi',
    'Tahirpur',
    'Maujpur',
    'Delhi',
    'North Garo Hills',
    'Meghalaya',
    'North Goa',
    'Goa',
    'North Tripura',
    'Tripura',
    'North West Delhi',
    'Pitampura',
    'Shalimar Bagh',
    'Delhi',
    'Nuapada',
    'Odisha',
    'Nuh',
    'Ferozepur Jhirka',
    'Punahana',
    'Taoru',
    'Haryana',
    'Osmanabad',
    'Maharashtra',
    'Pakke Kessang',
    'LemmiArunachal Pradesh',
    'Pakur',
    'Jharkhand',
    'Palakkad',
    'Kerala',
    'Palamu',
    'Jharkhand',
    'Palghar',
    'Carved out of Thane',
    'Vasai-Virar falls in Palgarh for example',
    'Maharashtra',
    'Pali',
    'Rajasthan',
    'Palwal',
    'Haryana',
    'Panch Mahals',
    'Godhra',
    'Halol',
    'Kalol',
    'Jambughoda',
    'Shahera',
    'Morva Hadaf',
    'Goghamba',
    'panchmahal',
    'Gujarat',
    'Panchkula',
    'KalkaHaryana',
    'Panipat',
    'SamalkhaHaryana',
    'Panna',
    'Madhya Pradesh',
    'Papum Pare',
    'YupiaArunachal Pradesh',
    'Parbhani',
    'Maharashtra',
    'Paschim Bardhaman',
    'West Bengal',
    'Pashchimi Singhbhum',
    'Jharkhand',
    'Patan',
    'Sidhpur',
    'Harij',
    'Radhanpur',
    'Sami',
    'Shankeshwar',
    'Santalpur',
    'Sarasvati',
    'Chanasma',
    'Gujarat',
    'Pathanamthitta',
    'Kerala',
    'Pathankot',
    'Punjab',
    'Patiala',
    'RajpuraPunjab',
    'Patna',
    'Bihar',
    'Pauri Garhwal',
    'Pauri',
    'Garhwal',
    'Kotdwara',
    'Dhumakot',
    'Uttarakhand',
    'Peddapalli',
    'Telangana',
    'Perambalur',
    'Perambalur',
    'Perumpuliur',
    'Perumpuliyur',
    'Tamil Nadu',
    'Peren',
    'Nagaland',
    'Phek',
    'Nagaland',
    'Pherzawl',
    'Manipur',
    'Pilibhit',
    'Uttar Pradesh',
    'Pithoragarh',
    'Dharchhula',
    'Didihat',
    'Gangolihat',
    'Uttarakhand',
    'Porbandar',
    'Ranavav',
    'Kutiyana',
    'Gujarat',
    'Prakasam',
    'OngoleAndhra Pradesh',
    'Pratapgarh',
    'Rajasthan',
    'Pratapgarh',
    'Uttar Pradesh',
    'Prayagraj',
    'Allahabad',
    'Illahabad',
    'Prayag',
    'Uttar Pradesh',
    'Puducherry',
    'PondicherryPuducherry',
    'Pudukkottai',
    'Thondaiman seemai',
    'The New Fort',
    'Tamil Nadu',
    'Pulwama',
    'Jammu and Kashmir',
    'Punch',
    'Jammu and Kashmir',
    'Pune',
    'Pune City',
    'Pune Rural',
    'Maharashtra',
    'Purba Bardhaman',
    'West Bengal',
    'Purbi Singhbhum',
    'JamshedpurJharkhand',
    'Puri',
    'Odisha',
    'Purnia',
    'Bihar',
    'Purulia',
    'puruliyaWest Bengal',
    'Rae Bareli',
    'RaebareliUttar Pradesh',
    'Raichur',
    'Karnataka',
    'Raigarh',
    'Dadar',
    'Dharamjaigarh',
    'Gharghoda',
    'Kharsia',
    'Raigarh',
    'Sarangarh',
    'Tamnar',
    'Tetla',
    'Chhattisgarh',
    'Raigarh',
    'Alibag',
    'Alibaug',
    'Maharashtra',
    'Raipur',
    'Naya Raipur',
    'Abhanpur',
    'Arang',
    'Baikunth',
    'Banarsi',
    'Bhanpuri',
    'Bhatgaon',
    'Birgaon',
    'Gobranawapara',
    'Gogaon',
    'Mowa',
    'Raipur',
    'Rajim',
    'Simga',
    'Tilda Newra',
    'Urla',
    'Chhattisgarh',
    'Raisen',
    'Madhya Pradesh',
    'Rajanna Sircilla',
    'SircillaTelangana',
    'Rajgarh',
    'Madhya Pradesh',
    'Rajkot',
    'Paddhari',
    'Lodhika',
    'Dhoraji',
    'Rajkot',
    'Jam Kandorna',
    'Upleta',
    'Jetpur',
    'Kotda Sangani',
    'Jasdan',
    'Vinchhiya',
    'Gondal',
    'Gujarat',
    'Rajnandgaon',
    'Ambagarh Chowki',
    'Chhuikhadan',
    'Dongargarh',
    'Dongergaon',
    'Gandai',
    'Khairagarh',
    'Rajnandgaon',
    'Chhattisgarh',
    'Rajouri',
    'Jammu and Kashmir',
    'Rajsamand',
    'Rajasthan',
    'Ramanagara',
    'Karnataka',
    'Ramanathapuram',
    'RamanadTamil Nadu',
    'Ramban',
    'Jammu and Kashmir',
    'Ramgarh',
    'Jharkhand',
    'Rampur',
    'Uttar Pradesh',
    'Ranchi',
    'Jharkhand',
    'Ranga Reddy',
    'ShamshabadTelangana',
    'Ratlam',
    'Madhya Pradesh',
    'Ratnagiri',
    'Maharashtra',
    'Rayagada',
    'Odisha',
    'Reasi',
    'Jammu and Kashmir',
    'Rewa',
    'Madhya Pradesh',
    'Rewari',
    'Kosli',
    'Bawal',
    'Haryana',
    'Ribhoi',
    'Meghalaya',
    'Rohtak',
    'Meham',
    'Rothasgarh',
    'Haryana',
    'Rohtas',
    'Bihar',
    'Rudraprayag',
    'Darmola',
    'Kedarnath',
    'Uttarakhand',
    'Rupnagar',
    'Punjab',
    'S.A.S. Nagar',
    'Sahibzada Ajit Singh Nagar',
    'Mohali',
    'Punjab',
    'S.P.S. Nellore',
    'Sri Potti Sriramulu Nellore',
    'Nellore',
    'Andhra Pradesh',
    'Sabar Kantha',
    'Himatnagar',
    'Idar',
    'Prantij',
    'Talod',
    'Khedbrahma',
    'Vadali',
    'Vijaynagar',
    'Poshina',
    'sabarkantha',
    'Gujarat',
    'Sagar',
    'Madhya Pradesh',
    'Saharanpur',
    'Uttar Pradesh',
    'Saharsa',
    'Bihar',
    'Sahibganj',
    'Jharkhand',
    'Saiha',
    'Mizoram',
    'Salem',
    'Tamil Nadu',
    'Samastipur',
    'Bihar',
    'Samba',
    'Jammu and Kashmir',
    'Sambalpur',
    'Odisha',
    'Sambhal',
    'Uttar Pradesh',
    'Sangareddy',
    'Telangana',
    'Sangli',
    'Maharashtra',
    'Sangrur',
    'Sunam',
    'Malerkotla',
    'Punjab',
    'Sant Kabir Nagar',
    'Uttar Pradesh',
    'Saraikela-Kharsawan',
    'Jharkhand',
    'Saran',
    'Bihar',
    'Satara',
    'MahabaleshwarMaharashtra',
    'Satna',
    'Madhya Pradesh',
    'Sawai Madhopur',
    'Rajasthan',
    'Sehore',
    'Madhya Pradesh',
    'Senapati',
    'Manipur',
    'Seoni',
    'Madhya Pradesh',
    'Serchhip',
    'Mizoram',
    'Shahdara',
    'Yamuna ViharDelhi',
    'Shahdol',
    'Madhya Pradesh',
    'Shahid Bhagat Singh Nagar',
    'Nawanshahr',
    'Punjab',
    'Shahjahanpur',
    'Uttar Pradesh',
    'Shajapur',
    'Madhya Pradesh',
    'Shamli',
    'Uttar Pradesh',
    'Sheikhpura',
    'Bihar',
    'Sheohar',
    'Bihar',
    'Sheopur',
    'Madhya Pradesh',
    'Shi Yomi',
    'TatoArunachal Pradesh',
    'Shimla',
    'Himachal Pradesh',
    'Shivamogga',
    'ShimogaKarnataka',
    'Shivpuri',
    'Madhya Pradesh',
    'Shrawasti',
    'Uttar Pradesh',
    'Shupiyan',
    'Jammu and Kashmir',
    'Siang',
    'Boleng',
    'Pangin',
    'Arunachal Pradesh',
    'Siddharthnagar',
    'Uttar Pradesh',
    'Siddipet',
    'Telangana',
    'Sidhi',
    'Madhya Pradesh',
    'Sikar',
    'Rajasthan',
    'Simdega',
    'Jharkhand',
    'Sindhudurg',
    'Maharashtra',
    'Singrauli',
    'Madhya Pradesh',
    'Sipahijala',
    'Tripura',
    'Sirmaur',
    'Himachal Pradesh',
    'Sirohi',
    'Rajasthan',
    'Sirsa',
    'Dabwali',
    'Rania',
    'Kalanwali',
    'Ellenabad',
    'Sirsapattan',
    'Haryana',
    'Sitamarhi',
    'Bihar',
    'Sitapur',
    'Uttar Pradesh',
    'Sivaganga',
    'Sivagangai SeemaiTamil Nadu',
    'Sivasagar',
    'Assam',
    'Siwan',
    'Bihar',
    'Solan',
    'Himachal Pradesh',
    'Solapur',
    'Maharashtra',
    'Sonbhadra',
    'Uttar Pradesh',
    'Sonipat',
    'Ganaur',
    'Gohana',
    'Sonepat',
    'Haryana',
    'Sonitpur',
    'Assam',
    'South 24 Parganas',
    '24 south parganasWest Bengal',
    'South Andaman',
    'Port Blair',
    'Andaman',
    'Andaman and Nicobar Islands',
    'South Delhi',
    'Dhaulakuan',
    'Lado Sarai',
    'Chatarpur',
    'Pushp Vihar',
    'Delhi',
    'South District',
    'Sikkim South District',
    'Sikkim South',
    'Sikkim',
    'South East Delhi',
    'Nizamuddin',
    'Lajpath Nagar',
    'Tuglakabad',
    'Badarpur',
    'South Ex',
    'Safdarjung',
    'Delhi',
    'South Garo Hills',
    'Meghalaya',
    'South Goa',
    'Goa',
    'South Salmara Mancachar',
    'Assam',
    'South Tripura',
    'Tripura',
    'South West Delhi',
    'Bijwasan',
    'Kapashera',
    'Palam',
    'Najafgarh',
    'Delhi',
    'South West Garo Hills',
    'Meghalaya',
    'South West Khasi Hills',
    'Meghalaya',
    'Sri Muktsar Sahib',
    'Muktsar',
    'Muktasar',
    'Punjab',
    'Srikakulam',
    'ChicacoleAndhra Pradesh',
    'Srinagar',
    'Jammu and Kashmir',
    'Subarnapur',
    'Odisha',
    'Sukma',
    'Chhindgarh',
    'Konta',
    'Sukma',
    'Chhattisgarh',
    'Sultanpur',
    'Uttar Pradesh',
    'Sundargarh',
    'rourkelaOdisha',
    'Supaul',
    'Bihar',
    'Surajpur',
    'Bishrampur',
    'Odagi',
    'Pratappur',
    'Prem Nagar',
    'Ramanuj Nagar',
    'Surajpur',
    'Chhattisgarh',
    'Surat',
    'Gujarat',
    'Surendranagar',
    'WadhwanGujarat',
    'Surguja',
    'Ambikapur',
    'Namna Kalan',
    'Phunderdihari',
    'Sitapur',
    'Telgaon',
    'Chhattisgarh',
    'Suryapet',
    'Telangana',
    'Tamenglong',
    'Manipur',
    'Tapi',
    'Vyara',
    'Songadh',
    'Nijhar',
    'Valod',
    'Uchhal',
    'Dolavan',
    'Kukarmunda',
    'Gujarat',
    'Tarn Taran',
    'Punjab',
    'Tawang',
    'Arunachal Pradesh',
    'Tehri Garhwal',
    'Ghanshali',
    'Deoprayag',
    'Tehri',
    'Dhanolti',
    'Uttarakhand',
    'Tengnoupal',
    'Manipur',
    'Thane',
    'Maharashtra',
    'Thanjavur',
    'TanjoreTamil Nadu',
    'The Dangs',
    'Subir',
    'Waghal',
    'Ahwa',
    'dang',
    'Gujarat',
    'The Nilgiris',
    'Nilgiri',
    'ooty',
    'Tamil Nadu',
    'Theni',
    'Tamil Nadu',
    'Thiruvallur',
    'Thiru evvulTamil Nadu',
    'Thiruvananthapuram',
    'Kerala',
    'Thiruvarur',
    'TiruvarurTamil Nadu',
    'Thoothukkudi',
    'TuticorinTamil Nadu',
    'Thoubal',
    'Manipur',
    'Thrissur',
    'Kerala',
    'Tikamgarh',
    'Madhya Pradesh',
    'Tinsukia',
    'Assam',
    'Tirap',
    'KhonsaArunachal Pradesh',
    'Tiruchirappalli',
    'Trichinopoly',
    'Trichy',
    'Tiruchi',
    'Tamil Nadu',
    'Tirunelveli',
    'Tenkasi district has been bifurcated from this districtTamil Nadu',
    'Tiruppur',
    'TirupurTamil Nadu',
    'Tiruvannamalai',
    'ArunaiTamil Nadu',
    'Tonk',
    'Rajasthan',
    'Tuensang',
    'Nagaland',
    'Tumakuru',
    'Karnataka',
    'Udaipur',
    'Rajasthan',
    'Udalguri',
    'Assam',
    'Udham Singh Nagar',
    'RudrapurUttarakhand',
    'Udhampur',
    'Jammu and Kashmir',
    'Udupi',
    'Karnataka',
    'Ujjain',
    'Nagda',
    'Badnagar',
    '',
    'Madhya Pradesh',
    'Ukhrul',
    'Manipur',
    'Umaria',
    'Madhya Pradesh',
    'Una',
    'Himachal Pradesh',
    'Unnao',
    'Uttar Pradesh',
    'Unokoti',
    'Tripura',
    'Upper Dibang Valley',
    'AniniArunachal Pradesh',
    'Upper Siang',
    'YingkiongArunachal Pradesh',
    'Upper Subansiri',
    'DaporijoArunachal Pradesh',
    'Uttar Bastar Kanker',
    'Antagarh',
    'Bhanupratappur',
    'Charama',
    'Kanker',
    'Narharpur',
    'Pakhanjur',
    'Chhattisgarh',
    'Uttar Dinajpur',
    'West Bengal',
    'Uttara Kannada',
    'Karnataka',
    'Uttarkashi',
    'Purola',
    'Yamunotri',
    'Gangotri',
    'Uttarakhand',
    'Vadodara',
    'Dabhoi',
    'Karjan',
    'Padra',
    'Savli',
    'Sinor',
    'Waghodia',
    'Gujarat',
    'Vaishali',
    'Bihar',
    'Valsad',
    'Pardi',
    'Vapi',
    'Dharampur',
    'Kaparada',
    'Umbergaon',
    'Gujarat',
    'Varanasi',
    'Banaras',
    'Benaras',
    'Kashi',
    'Uttar Pradesh',
    'Vellore',
    'Vellur',
    'Tamil Nadu',
    'Vidisha',
    'Madhya Pradesh',
    'Vijayapura',
    'Karnataka',
    'Vikarabad',
    'Telangana',
    'Viluppuram',
    'Kallakurichi ',
    'Virudhunagar',
    'VirudupattiTamil Nadu',
    'Visakhapatnam',
    'VizagapatamAndhra Pradesh',
    'Vizianagaram',
    'VijayanagaramAndhra Pradesh',
    'Wanaparthy',
    'Telangana',
    'Warangal Rural',
    'GeesugondaTelangana',
    'Warangal Urban',
    'Warangal city',
    'warangal',
    'Telangana',
    'Wardha',
    'Maharashtra',
    'Washim',
    'Maharashtra',
    'Wayanad',
    'Kerala',
    'West Champaran',
    'Bihar',
    'West Delhi',
    'Punjabi Bagh',
    'Paschim Vihar',
    'Janakpuri',
    'Kirti Nagar',
    'Delhi',
    'West District',
    'Sikkim West District',
    'Sikkim West',
    'Sikkim',
    'West Garo Hills',
    'Meghalaya',
    'West Godavari',
    'Paschima Godavari Jilla',
    'Eluru',
    'Andhra Pradesh',
    'West Jaintia Hills',
    'Meghalaya',
    'West Kameng',
    'BomdilaArunachal Pradesh',
    'West Karbi Anglong',
    'Assam',
    'West Khasi Hills',
    'Meghalaya',
    'West Siang',
    'Aalo',
    'Along',
    'Arunachal Pradesh',
    'West Tripura',
    'Tripura',
    'Wokha',
    'Nagaland',
    'Y.S.R.',
    'Kadapa',
    'Cuddapah',
    'Andhra Pradesh',
    'Yadadri Bhuvanagiri',
    'BhongiriTelangana',
    'Yadgir',
    'Karnataka',
    'Yamunanagar',
    'Jagadhri',
    'Chhachhrauli',
    'Sadhaura',
    'Adi Badri',
    'Bilaspur',
    'Radaur',
    'Haryana',
    'Yanam',
    'Puducherry',
    'Yavatmal',
    'Maharashtra',
    'Zunheboto',
    'Nagaland',
  ],
  'en-US': [
    'active',
    'recovered',
    'deceased',
    'confirmed',
    'active cases',
    'recovered cases',
    'deceased cases',
    'confirmed cases',
  ],
};
// set the above hints
Slang.setASRHints(hints);

const uiObs = (UIState) => {
  if (UIState.selectedLocale !== selectedLocale) {
    selectedLocale = UIState.selectedLocale;
    localStorage.setItem('slangLocale', selectedLocale);
  }
};
Slang.registerUIObserver(uiObs);

const replyValues = ({
  caseFor,
  dataTypeQuery,
  districtQuery,
  stateQuery,
  orderQuery,
  number,
}) => {
  console.log(caseFor, dataTypeQuery, districtQuery, stateQuery, number);
  switch (caseFor) {
    case 'replyWithOrder':
      return (
        'The state with the ' +
        orderQuery +
        ' ' +
        dataTypeQuery +
        ' cases in India is ' +
        stateQuery +
        ' with ' +
        number +
        ' cases'
      );
    case 'replyWithDistricts':
      if (selectedLocale === 'hi-IN') {
        return districtQuery + ' में पुष्ट मामलो की संख्या ' + number + ' है ';
      }
      return 'Confirmed cases in ' + districtQuery + ' is ' + number;
    case 'replyWithStates':
      if (selectedLocale === 'hi-IN') {
        switch (dataTypeQuery) {
          case 'active':
            return stateQuery + ' मैं ऐक्टिव कसेस की संख्या ' + number + ' है ';
          case 'confirmed':
            return stateQuery + ' में पुष्ट मामलो की संख्या ' + number + ' है ';
          case 'recovered':
            return (
              stateQuery +
              ' में स्वस्थ होनेवाले मामलों की संख्या ' +
              number +
              ' है '
            );
          case 'deceased':
            return stateQuery + ' में ' + number + ' लोगो की मौत हो चुकी हैं ';
          default:
            console.log('data type not found');
            break;
        }
      }
      return dataTypeQuery + ' cases in ' + stateQuery + ' is ' + number;
    case 'noDataDistrict':
      if (selectedLocale === 'hi-IN') {
        return 'माफ़ करिये ।अभी हमारे पास ज़िला स्तर पर ख़ाली पुष्ट मामलों की संख्या है';
      } else {
        return 'Sorry. Data is available only for confirmed cases currently at a district level';
      }
    case 'noDataState':
      if (selectedLocale === 'hi-IN') {
        return 'माफ़ करिये अभी हमारे पास इस का उत्तर नहीं है।';
      } else {
        return "We couldn't find data for your query.";
      }

    default:
      return false;
  }
};

function SlangInterface(props) {
  const {states, stateDistrictWiseData} = props;

  theDistricts = Object.keys(stateDistrictWiseData).reduce((acc, state) => {
    const dist = Object.keys(stateDistrictWiseData[state]['districtData'])
      .filter((i) => i.toLowerCase() !== 'unknown')
      .map((district) => ({
        name: district,
        state: state,
        ...stateDistrictWiseData[state]['districtData'][district],
      }));
    return [...acc, ...dist];
  }, []);

  let index;
  let district;
  let state;

  const replyWithStates = (intent) => {
    index = district = state = undefined;

    const stateQuery =
      intent.getEntity('state').isResolved &&
      intent.getEntity('state').value.trim().toLowerCase();
    const dataTypeQuery = intent.getEntity('data_type').isResolved
      ? intent.getEntity('data_type').value.trim().toLowerCase()
      : 'confirmed';

    const theNumber =
      stateQuery &&
      states.find((item, i) => {
        index = i;
        return item.state.trim().toLowerCase() === stateQuery;
      });

    console.log('dataTypeQuery = ' + dataTypeQuery);
    console.log('stateQuery = ' + stateQuery);
    console.log(theNumber);
    console.log('theNumber[state] = ' + theNumber[dataTypeQuery]);
    if (dataTypeQuery && stateQuery && theNumber && theNumber[dataTypeQuery]) {
      props.onHighlightState(theNumber, index);
      window.location.hash = '#MapStats';
      const prompt = replyValues({
        caseFor: 'replyWithStates',
        dataTypeQuery,
        stateQuery,
        number: theNumber[dataTypeQuery],
      });
      Slang.startConversation(prompt, true);
    } else {
      const prompt = replyValues({
        caseFor: 'noDataState',
      });

      Slang.startConversation(prompt, true);
    }

    window.location.hash = '#_';
    index = district = state = undefined;
  };

  const replyWithDistricts = (intent) => {
    index = district = state = undefined;
    const districtQuery =
      intent.getEntity('district').isResolved &&
      intent.getEntity('district').value.trim().toLowerCase();
    const dataTypeQuery =
      intent.getEntity('data_type').isResolved &&
      intent.getEntity('data_type').value.trim().toLowerCase();
    if (dataTypeQuery && dataTypeQuery !== 'confirmed') {
      const prompt = replyValues({
        caseFor: 'noDataDistrict',
      });

      Slang.startConversation(prompt, true);
    } else {
      const theNumberDistrictConfirmed =
        districtQuery &&
        theDistricts.reduce((acc, item) => {
          if (item.name.trim().toLowerCase() === districtQuery) {
            index = item.state;
            district = item.name;
            state = item;
            return item.confirmed;
          }
          return acc;
        }, '');
      if (theNumberDistrictConfirmed) {
        window.location.hash = '#MapStats';
        index = states.findIndex((x) => x.state === index);
        props.onHighlightDistrict(district, state, index);
        const prompt = replyValues({
          caseFor: 'replyWithDistricts',
          districtQuery,
          number: theNumberDistrictConfirmed,
        });

        Slang.startConversation(prompt, true);
      } else {
        const prompt = replyValues({
          caseFor: 'noDataState',
        });
        Slang.startConversation(prompt, true);
      }
    }
    window.location.hash = '#_';
  };

  const replyWithCountry = (intent) => {
    index = district = state = undefined;

    let stateQuery = 'total';
    const countryQuery = intent.getEntity('country').isResolved
      ? intent.getEntity('country').value.trim()
      : 'India';
    const orderQuery =
      intent.getEntity('order').isResolved &&
      intent.getEntity('order').value.trim().toLowerCase();
    const dataTypeQuery = intent.getEntity('data_type').isResolved
      ? intent.getEntity('data_type').value.trim().toLowerCase()
      : 'confirmed';

    console.log('countryQuery = ' + countryQuery);
    if (countryQuery !== 'India') {
      Slang.startConversation('We curently support data only for India', true);
    } else if (orderQuery) {
      console.log('orderQuery = ' + orderQuery);
      console.log('dataTypeQuery = ' + dataTypeQuery);
      let highestState = states[1].state;
      let highestValue = parseInt(states[1][dataTypeQuery]);
      let lowestState = states[1].state;
      let lowestValue = parseInt(states[1][dataTypeQuery]);

      states.forEach((item, i) => {
        if (item.state === 'Total') return;

        if (parseInt(item[dataTypeQuery]) > highestValue) {
          highestValue = parseInt(item[dataTypeQuery]);
          highestState = item.state.trim().toLowerCase();
        }
        if (parseInt(item[dataTypeQuery]) < lowestValue) {
          lowestValue = parseInt(item[dataTypeQuery]);
          lowestState = item.state.trim().toLowerCase();
        }
      });

      let numberQuery;

      if (orderQuery === 'highest') {
        stateQuery = highestState;
        numberQuery = highestValue;
      } else {
        stateQuery = lowestState;
        numberQuery = lowestValue;
      }

      // props.onHighlightState(theNumber, index);
      window.location.hash = '#MapStats';
      const prompt = replyValues({
        caseFor: 'replyWithOrder',
        dataTypeQuery,
        stateQuery,
        orderQuery: orderQuery,
        number: numberQuery,
      });
      Slang.startConversation(prompt, true);
    } else {
      console.log('India query = ' + dataTypeQuery);
      const theNumber =
        stateQuery &&
        states.find((item, i) => {
          index = i;
          return item.state.trim().toLowerCase() === stateQuery;
        });

      console.log('dataTypeQuery = ' + dataTypeQuery);
      console.log('stateQuery = ' + stateQuery);
      console.log(theNumber);
      console.log('theNumber[state] = ' + theNumber[dataTypeQuery]);

      if (
        dataTypeQuery &&
        stateQuery &&
        theNumber &&
        theNumber[dataTypeQuery]
      ) {
        props.onHighlightState(theNumber, index);
        window.location.hash = '#MapStats';
        const prompt = replyValues({
          caseFor: 'replyWithStates',
          dataTypeQuery,
          stateQuery: 'India',
          number: theNumber[dataTypeQuery],
        });
        Slang.startConversation(prompt, true);
      } else {
        const prompt = replyValues({
          caseFor: 'noDataState',
        });

        Slang.startConversation(prompt, true);
      }
    }

    window.location.hash = '#_';
    index = district = state = undefined;
  };

  try {
    Slang.setOnUtteranceDetected((string) => {
      console.log('utterance - ' + string);
      ReactGA.event({
        category: 'Slang events',
        action: 'trigger click',
      });
    });
    Slang.setIntentActionHandler((intent) => {
      console.log(intent);
      switch (intent.name) {
        case 'reply_with_districts':
          replyWithDistricts(intent);
          return true;

        case 'reply_with_states':
          replyWithStates(intent);
          return true;

        case 'reply_with_country':
          replyWithCountry(intent);
          return true;

        default:
          return false;
      }
    });
  } catch (error) {
    console.log(error);
  }

  return null;
}

// This function is used in the conjunction with the Patients DB of the dashboard to choose the state and or district while searching
export function SlangPatients(props) {
  // read the handleFilters prop of the component
  const {handleFilters} = props;

  try {
    // set the intent handle with slang to perform tasks when an intent from the user is detected.
    Slang.setIntentActionHandler((intent) => {
      switch (intent.name) {
        case 'reply_with_districts':
          // read the district spoken by the user.
          const districtQuery =
            intent.getEntity('district').isResolved &&
            intent.getEntity('district').value.trim(); // .toLowerCase()
          // get the state where is district is in from the list available on the dashboard.

          const theState =
            districtQuery &&
            theDistricts.reduce((acc, item) => {
              if (
                item.name.trim().toLowerCase() === districtQuery.toLowerCase()
              ) {
                return item.state;
              }
              return acc;
            }, '');
          if (theState) {
            handleFilters('detectedstate', theState);
            handleFilters('detecteddistrict', districtQuery);
          }
          return true;
        case 'reply_with_states':
          const stateQuery =
            intent.getEntity('state').isResolved &&
            intent.getEntity('state').value.trim(); // .toLowerCase();
          if (stateQuery) handleFilters('detectedstate', stateQuery);
          return true;
        default:
          return false;
      }
    });
  } catch (error) {
    console.log(error);
  }

  return null;
}

export default SlangInterface;
